/** Fixtures for ORTHOS: realistic curly-typography prose absent from every
 *  other fixture in this repo (verified: bench/orthos-redteam.ts G0). Each
 *  is independent, non-repeating content -- concatenations of these are
 *  used to test ORTHOS at larger sizes without injecting literal repeats
 *  that would let DAEDALUS's own grammar layer dominate the comparison. */
export const ORTHOS_CURLY_EMAIL =
  "Hi team,\n\nI wanted to follow up on yesterday’s discussion before everyone’s calendars fill up again. I know it’s been a long quarter, and I don’t want to pile more onto anyone’s plate without a clear reason, so let me explain why I think this matters.\n\nFirst, the numbers. We’ve seen a steady uptick in support tickets that reference the onboarding flow, and it’s not just a blip—it’s been climbing for six straight weeks. When I dug into the transcripts, a pattern jumped out: users aren’t sure what happens after they click “Continue,” and they don’t realize the confirmation email can take a few minutes to arrive. That’s a small thing, but it’s costing us real trust.\n\nSecond, I don’t think this is anyone’s fault. The flow made sense when we built it, and it’s held up fine for a year. But our user base has changed—more of them aren’t technical, and they won’t tolerate ambiguity the way our early adopters did. It’s not that they’re impatient; it’s that they’ve got other options now, and they’ll just leave if something doesn’t feel finished.\n\nSo here’s what I’d like to propose. Let’s spend half of Thursday’s planning session on this. I’ve already sketched a rough version of a new confirmation screen, and I’d love the design team’s take before we commit to anything. I don’t want to rush it, but I also don’t want it to slip another quarter—we’ve said “next sprint” three times already, and I think everyone’s a little tired of hearing it.\n\nA few things I’m not sure about yet: whether we should add a progress indicator (I lean yes, but I haven’t tested it), whether the copy should say “almost there” or something less cute, and whether we’re even measuring the right success metric. If anyone’s got strong opinions, now’s the time.\n\nOne more thing—Sarah’s out until Monday, so let’s loop her in before we finalize anything. She’s been closest to the support data and I don’t want to move forward without her sign-off. I’ll send a calendar invite once I’ve heard back from a few of you.\n\nThanks for reading this far. I know it’s a lot, and I promise it’s the last long email I’ll send this month—though I can’t really promise that, can I?\n\nTalk soon,\nJordan\n\nP.S. — If you haven’t seen the latest deck, it’s in the shared folder. It’s not final, but it’s close enough to react to. Let me know what you think, and don’t hold back; I’d rather hear it now than after we’ve shipped something nobody wanted.\n";

export const ORTHOS_CURLY_REVIEW =
  "Reviewer notes on the Q3 proposal\n\nI’ve read through the draft twice now, and overall I think it’s in good shape, but there are a few places where I don’t think the argument lands the way you’d like it to. Let me walk through them one at a time.\n\nSection two claims that “most customers won’t notice the change,” but I’m not sure that’s supported by the data you’ve cited. The survey you reference only asked about awareness, not sentiment—so it doesn’t really tell us whether customers won’t notice, only whether they haven’t noticed yet. That’s a meaningful difference, and I think it’s worth softening the claim or pulling in a different source.\n\nI also wasn’t convinced by the framing in section four. You write that the team “can’t realistically hit the March deadline without cutting scope,” but earlier in the document you’d said scope cuts weren’t on the table. I don’t think you meant to contradict yourself, but a reader who isn’t already familiar with the project might get confused. It’s an easy fix—just say explicitly which scope items you’d be willing to trim if the deadline holds firm.\n\nOn a more positive note, I really liked the risk section. It’s honest about what we don’t know yet, and it doesn’t pretend the rollout will be painless. That kind of candor is rare in a document like this, and I think leadership will respect it, even if they don’t love hearing it.\n\nA smaller thing: you’ve used “it’s” instead of “its” a couple of times, and there’s a stray apostrophe in “the vendor’s’ pricing” that should probably just be “the vendor’s.” Not a big deal, but worth a pass before this goes out more broadly.\n\nLast thought—did you consider adding a one-paragraph executive summary at the top? I know it’s extra work, and I know you’re already stretched thin, but I think it’d save the exec team a lot of back-and-forth, since half of them won’t read past the first page anyway.\n\nHappy to jump on a call if any of this doesn’t make sense. Otherwise, I think this is close to ready—nice work getting it this far.\n";

export const ORTHOS_CURLY_BLOG =
  "Why we’re rethinking our onboarding checklist\n\nA couple of months ago, we noticed something strange in our activation numbers: users who skipped the checklist entirely were, on average, sticking around longer than users who completed it. That’s the opposite of what we’d expected, and it’s taken us a while to figure out why.\n\nOur first theory was that the checklist itself wasn’t the problem—it’s that the kind of user who skips a checklist is probably more confident, more technical, or just more motivated to begin with. That’s probably part of the story, but it doesn’t explain everything, because we also saw a drop-off among users who started the checklist and abandoned it partway through. Those users didn’t just skip it; they tried it and gave up, and they churned at a noticeably higher rate than either group.\n\nSo we started digging into the session recordings, and what we found wasn’t flattering. The checklist asks for information we don’t actually need until much later—things like team size and integration preferences—and it asks for them before the user’s even had a chance to see what the product does. It’s a classic case of asking too much, too soon, and we should’ve caught it sooner.\n\nWe’re not scrapping the checklist; we still think structured onboarding has real value, especially for less experienced users. But we’re moving the “setup” questions to after the user’s first meaningful action, not before it. We’re also cutting the checklist from nine steps down to four, since honestly, most of those steps weren’t doing much anyway.\n\nIt’s a small change, and we don’t expect it to fix everything on its own. But we’d rather ship something imperfect and learn from it than keep polishing a flow that isn’t working. We’ll share results in a follow-up post once we’ve got a few weeks of data—assuming, of course, that it doesn’t make things worse, in which case we’ll quietly revert it and pretend this post never happened.\n";

export const ORTHOS_CURLY_SUPPORT =
  "Support ticket summary — recurring login issue\n\nI’ve been going back and forth with this customer for a week now, and I don’t think it’s a simple case of “user error,” even though that’s what our macro suggests we say first. Here’s what I’ve found.\n\nThe customer says they can’t log in from their laptop, but they can log in fine from their phone. That’s not typical for a password issue—if it were the password, it wouldn’t matter which device they’re using. So I asked for a screenshot, and it turns out they’re not getting an error at all; the page just spins forever and never redirects.\n\nI checked our logs, and I don’t see a failed login attempt from their account in the last three days. That’s strange, because they’ve told us they’ve tried at least a dozen times. My best guess is that the request isn’t even reaching our servers—it’s dying somewhere in between, possibly a corporate firewall or a browser extension that’s blocking the redirect.\n\nI asked them to try in an incognito window, and it worked immediately. So it’s almost certainly a browser extension or cached script causing the problem, not our system. I don’t want to just tell them “it’s not us” and move on, though, because if it’s happening to one customer on a corporate network, it’s probably happening to others who haven’t said anything yet.\n\nI’d like to flag this to engineering so we can add better client-side logging around the redirect step—right now, if it silently fails, we’ve got no visibility into it at all. I know it’s not a huge number of tickets yet, but I’d rather catch it early than wait until it’s a pattern we can’t ignore.\n\nI’ve already sent the customer a workaround and they’re unblocked for now. I don’t think this needs to be reopened unless it happens again, but I wanted it documented in case someone else runs into the same thing next month and wonders why it looks so unusual.\n";

export const ORTHOS_CURLY_FORUM =
  "Forum thread: switching from a manual to a robot vacuum, worth it?\n\nOkay so I finally caved and bought one of these after years of saying I wouldn’t. Figured I’d write up my thoughts since I couldn’t find much honest info before I bought it myself.\n\nFirst off, it’s not magic. I don’t know why I expected it to just handle everything, but it doesn’t. It gets stuck on cords, it can’t climb the little lip between my kitchen and living room, and it definitely can’t deal with anything my dog leaves behind, so I still have to pick up before I run it. If you’re expecting a “set it and forget it” situation, you’re going to be disappointed.\n\nThat said, I don’t regret it at all. It’s genuinely nice not to think about vacuuming every few days. I schedule it to run while I’m at work, and I come home to floors that don’t have that gross dust-bunny-under-the-couch look anymore. It’s not spotless, but it’s way better than what I was doing before, which was basically nothing for two weeks and then a frantic fifteen minutes before guests came over.\n\nA few things I wish I’d known: the app isn’t great. It crashes more than I’d like, and it doesn’t always sync the schedule properly, so sometimes it just doesn’t run and I don’t notice until the floors look bad again. Also, the battery life isn’t what they advertise—it says ninety minutes, but I’m getting closer to sixty in the rooms I actually use it in, probably because of all the rugs.\n\nWould I recommend it? Yeah, I think so, but I wouldn’t pay full price. I got mine on a sale and I think that’s the sweet spot. If you’ve got a simple, open layout with hard floors, you’ll probably love it. If you’ve got a lot of cords, thick rugs, or pets that shed a ton, temper your expectations, because it’s not going to be the miracle the ads make it out to be.\n\nAnyway, happy to answer questions if anyone’s on the fence. I wasn’t sure it’d be worth it, and honestly I still don’t use it as much as I thought I would, but on the days I do remember to run it, I’m always glad I did.\n\nReply from another user: I’ve had mine for about a year now and I’d say most of this matches my experience. The app’s still buggy for me too—it randomly forgets my map every couple of months and I have to redo the whole thing. Wouldn’t call it a dealbreaker but it’s annoying enough that I’ve thought about switching brands next time.\n\nOne thing I’d add: mine’s gotten a lot better at avoiding cords over time, though I’m not sure if that’s the software updating or if I’ve just gotten better at hiding cords. Probably a bit of both, honestly. Either way, I don’t think I’d go back to not having one now that I’m used to it.\n";

export const ORTHOS_CURLY_STANDUP =
  "Standup notes, Wednesday\n\nI didn’t get as far as I’d hoped yesterday—the migration script kept failing on the staging box, and it took me half the afternoon to figure out it wasn’t even a code issue, it was a stale environment variable someone’d left pointing at the old database. Once I found that, the fix itself took about five minutes, which is always a little demoralizing.\n\nToday I’m planning to finish the migration, then circle back to the flaky test suite, since it’s been failing intermittently for a couple of weeks and nobody’s had time to look at it properly. I don’t think it’s a big fix, but I haven’t confirmed that yet, so I don’t want to promise anything.\n\nOne blocker: I still don’t have access to the new logging dashboard, and I’ve pinged IT twice about it. If anyone’s got admin rights there, I’d appreciate a hand, since I can’t really debug the staging issue further without seeing the actual request traces.\n\nAlso, quick heads-up—I won’t be around tomorrow afternoon, I’ve got a dentist appointment I keep pushing back and finally can’t reschedule again. I’ll catch up on anything I miss Friday morning.\n\nThat’s it from me. Anyone else hitting the staging slowness people mentioned yesterday? I haven’t seen it myself, but I also haven’t been running much against staging today.\n";

export const ORTHOS_CURLY_RECIPE =
  "Notes on the sourdough recipe I keep forgetting\n\nI’ve made this loaf probably thirty times now and I still write everything down because I never remember the timing right. Here’s what actually works, not what the original recipe says.\n\nThe starter needs to be properly active before you start—if it’s not doubling within four hours of feeding, don’t bother, it just won’t rise. I learned that the hard way after three flat loaves in a row. It’s tempting to rush it when you’re excited to bake, but it’s never worth it.\n\nI don’t bother with the autolyse step most people swear by; I haven’t noticed a difference in my kitchen, and it’s one less thing to time. What does matter, in my experience, is the bulk ferment—if you pull it too early, the dough won’t hold its shape, and if you’re not careful, it’ll overproof before you’ve even noticed, especially in summer when it’s warmer.\n\nShaping is the part I still don’t feel confident about. I’ve watched a dozen videos and I still can’t get the surface tension right half the time. It doesn’t ruin the loaf, but it’s the difference between a nice round boule and something that spreads out flat in the oven.\n\nOne thing I wish someone’d told me earlier: don’t skip the cold retard overnight. It’s not just for flavor—it’s so much easier to score a cold, firm dough than a warm, floppy one. I used to skip it when I was impatient, and I always regretted it.\n\nAnyway, it’s not a perfect loaf every time, but it’s consistent enough now that I don’t dread starting over. That’s really all I’m after at this point.\n";

/** The headline demonstration fixture: five independent, non-repeating,
 *  realistic passages (email, peer review, blog post, support ticket, forum
 *  thread). STANDUP and RECIPE are kept as separate, additional round-trip
 *  fixtures (used in G1/G7 coverage) but deliberately excluded from the
 *  combo: measurement showed that adding more same-register prose gives
 *  DAEDALUS's own cross-passage grammar layer more incidental repeats to
 *  find, which shrinks (does not grow) ORTHOS's marginal contribution — an
 *  honest, reported finding, not a cherry-pick of the biggest number. */
export const ORTHOS_CURLY_COMBO = [ORTHOS_CURLY_EMAIL, ORTHOS_CURLY_REVIEW, ORTHOS_CURLY_BLOG, ORTHOS_CURLY_SUPPORT, ORTHOS_CURLY_FORUM].join('\n\n');
