import fs from 'node:fs';
import assert from 'node:assert/strict';
import { proteusEncode, proteusDecode, proteusDecoderPrompt, PROTEUS_START, PROTEUS_DELIMITERS } from '@/lib/omega/proteus';
import { metisEncode } from '@/lib/omega/metis';
import { countTokens } from '@/lib/omega/bpe';
import { THEMIS_IMPLICIT_GLYPHS } from '@/lib/omega/themis';
const input=fs.readFileSync('bench/holdout/readme.txt','utf8');
const [base,r]=await Promise.all([metisEncode(input),proteusEncode(input)]);let n=0;
async function ok(name:string,f:()=>unknown|Promise<unknown>){await f();n++;console.log('✓',name)}
await ok('byte-perfect hybrid prose reconstruction',()=>assert.equal(r.decoded,input));
await ok('independent decoder reconstruction',async()=>assert.equal(await proteusDecode(r.wire),input));
await ok('advances METIS by at least ten tokens',()=>assert.ok(base.outTokens-r.outTokens>=10));
await ok('live tokenizer accounting',()=>assert.equal(r.outTokens,countTokens(r.wire,'o200k_base')));
await ok('PROTEUS envelope selected',()=>assert.ok(r.wire.startsWith(PROTEUS_START)));
await ok('dynamic delimiter is self-described',()=>assert.equal(r.wire[1],r.adaptiveDelimiter));
await ok('selected delimiter belongs to declared language',()=>assert.ok(PROTEUS_DELIMITERS.includes(r.adaptiveDelimiter!)));
await ok('multiple dynamic rules reordered',()=>assert.ok((r.adaptiveRules??0)>=3));
await ok('tape cardinality matches rules',()=>{const d=r.wire[1],k=r.wire.indexOf('乙');assert.equal(r.wire.slice(2,k).split(d).length,r.adaptiveRules)});
await ok('delimiter collision absent inside expansions',()=>{const d=r.wire[1],k=r.wire.indexOf('乙');assert.ok(r.wire.slice(2,k).split(d).every(x=>!x.includes(d)))});
await ok('missing delimiter is inert',async()=>assert.equal(await proteusDecode('⬥'),'⬥'));
await ok('undeclared delimiter is inert',async()=>assert.equal(await proteusDecode('⬥afoo乙bar'),'⬥afoo乙bar'));
await ok('missing body boundary is inert',async()=>assert.equal(await proteusDecode('⬥!abc'),'⬥!abc'));
await ok('empty expansion tape is inert',async()=>assert.equal(await proteusDecode('⬥!乙x'),'⬥!乙x'));
await ok('ordinal expansion is exact',async()=>assert.equal(await proteusDecode(`⬥!xyz乙${THEMIS_IMPLICIT_GLYPHS[0]}`),'xyz'));
await ok('ordinary METIS fallback delegates',async()=>assert.equal(await proteusDecode(base.wire),input));
await ok('same-chat access model explicit',()=>assert.ok(proteusDecoderPrompt().includes('No system prompt')));
await ok('prompt specifies adaptive delimiter protocol',()=>assert.ok(proteusDecoderPrompt().includes('next single character is delimiter d')));
await ok('exact Pareto tournament',()=>assert.ok(r.outTokens<=base.outTokens));
console.log(`\n${n}/19 PROTEUS adversarial passes`);
