/** Fixtures for STENTOR: realistic "sustained uppercase" prose absent from
 *  every other fixture in this repo (verified: bench/stentor-redteam.ts G0).
 *  Each simulates a genuine, common real-world genre: an accidental
 *  caps-lock submission (support ticket, forum post, email, product review,
 *  chat message). Each is independent, non-repeating content. */
export const STENTOR_CAPS_SUPPORT =
  "I AM WRITING BECAUSE MY ACCOUNT WAS CHARGED TWICE THIS MONTH AND I DO NOT UNDERSTAND WHY. I ONLY SIGNED UP FOR ONE SUBSCRIPTION BUT MY BANK STATEMENT SHOWS TWO SEPARATE CHARGES ON THE SAME DAY. I HAVE BEEN A CUSTOMER FOR THREE YEARS AND THIS HAS NEVER HAPPENED BEFORE. PLEASE LOOK INTO THIS AS SOON AS POSSIBLE BECAUSE I NEED THE EXTRA MONEY REFUNDED BEFORE THE END OF THE WEEK. I TRIED CALLING THE SUPPORT LINE BUT WAS ON HOLD FOR OVER AN HOUR AND HAD TO HANG UP BECAUSE I NEEDED TO GET BACK TO WORK. IF SOMEONE COULD EMAIL ME DIRECTLY WITH AN UPDATE I WOULD REALLY APPRECIATE IT. THANK YOU FOR YOUR TIME.";

export const STENTOR_CAPS_FORUM =
  "SO I FINALLY UPGRADED MY GRAPHICS CARD LAST WEEKEND AND HONESTLY I DO NOT KNOW WHY I WAITED THIS LONG. THE DIFFERENCE IN FRAME RATE IS HUGE COMPARED TO MY OLD SETUP. I WAS WORRIED THE NEW CARD WOULDNT FIT IN MY CASE BUT IT SLID RIGHT IN WITH ROOM TO SPARE. THE ONLY ISSUE I HAD WAS THE DRIVER INSTALL FREEZING PARTWAY THROUGH BUT A RESTART FIXED IT. IF ANYONE ELSE IS ON THE FENCE ABOUT UPGRADING I WOULD SAY JUST DO IT, ESPECIALLY IF YOUR CURRENT CARD IS MORE THAN FOUR YEARS OLD. HAPPY TO ANSWER QUESTIONS IF ANYONE IS THINKING ABOUT THE SAME UPGRADE.";

export const STENTOR_CAPS_EMAIL =
  "HI EVERYONE, JUST A QUICK NOTE TO SAY THE OFFICE MOVE HAS BEEN PUSHED BACK TWO WEEKS BECAUSE THE NEW BUILDING ISNT READY YET. WE WILL STAY IN THE CURRENT SPACE UNTIL THE FIFTEENTH AND THEN TRANSITION OVER THE FOLLOWING WEEKEND. PLEASE HOLD OFF ON PACKING ANYTHING UNTIL YOU HEAR FROM FACILITIES DIRECTLY. I KNOW THIS IS FRUSTRATING GIVEN HOW MANY TIMES THE DATE HAS CHANGED BUT WE WANT TO MAKE SURE EVERYTHING IS ACTUALLY READY THIS TIME. THANKS FOR YOUR PATIENCE.";

export const STENTOR_CAPS_REVIEW =
  "I BOUGHT THIS BLENDER THREE MONTHS AGO AND IT HAS COMPLETELY CHANGED MY MORNING ROUTINE. IT IS LOUD BUT NOT UNBEARABLY SO AND IT CRUSHES ICE WITHOUT ANY PROBLEM WHICH MY OLD BLENDER COULD NEVER DO. THE ONLY DOWNSIDE IS THE PITCHER IS A LITTLE AWKWARD TO CLEAN AROUND THE BLADE BASE. STILL, FOR THE PRICE I THINK THIS IS A GREAT VALUE AND I WOULD RECOMMEND IT TO ANYONE WHO MAKES SMOOTHIES REGULARLY.";

export const STENTOR_CAPS_CHAT =
  "HEY SORRY FOR THE ALL CAPS MY CAPS LOCK IS STUCK AND I CANT FIGURE OUT HOW TO TURN IT OFF ON THIS LAPTOP. ANYWAY I WANTED TO ASK IF YOU ARE STILL FREE FOR LUNCH TOMORROW OR IF SOMETHING CAME UP. LET ME KNOW WHENEVER YOU GET A CHANCE, NO RUSH AT ALL.";

/** Realistic "occasional emphasis in normal prose" fixture, used to show
 *  the honest negative-space case: short, scattered ALL-CAPS phrases inside
 *  otherwise mixed-case prose almost never clear the sentinel overhead, so
 *  STENTOR should mostly decline to apply here (verified in G6/G9-neg). */
export const STENTOR_MIXED_EMPHASIS =
  "Hi team,\n\nI'm following up on ticket #4471. The customer reports that after our last deploy, their dashboard stopped loading entirely.\n\nIMPORTANT: THIS IS AFFECTING MULTIPLE ENTERPRISE CUSTOMERS, NOT JUST ONE ACCOUNT. Please treat this as high priority.\n\nI checked the logs and found repeated timeout errors starting right after the 2:00 PM release. My best guess is the new caching layer is misconfigured for accounts with more than 500 seats, since that's the pattern across the four reports we've gotten so far.\n\nDO NOT ROLL BACK YET -- we think a config flag change can fix this without a full redeploy. I'm testing that now in staging.\n\nI'll update this thread within the hour. If anyone has seen something similar before, please chime in.\n\nThanks,\nPriya";

/** Realistic, genuine, famous, heavily-memorized ALL-CAPS legal boilerplate
 *  (the classic UCC-2-316-style software warranty disclaimer). Used to show
 *  the honest negative-space case: o200k_base has dedicated efficient
 *  merges for this exact famous string regardless of case, so STENTOR
 *  should show near-zero benefit here (verified in G6/G9-neg). */
export const STENTOR_LEGAL_BOILERPLATE =
  'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.';

/** A SINGLE realistic caps-lock-accident document (one formal complaint
 *  letter, ~1250 chars / 326 raw tokens) -- the strongest "one real message"
 *  demonstration: a real user pasting ONE long message that got typed with
 *  caps lock stuck on, not an artificially concatenated combo of several. */
export const STENTOR_CAPS_LONG_COMPLAINT =
  "I AM WRITING TO FILE A FORMAL COMPLAINT ABOUT THE SERVICE I RECEIVED AT YOUR DOWNTOWN LOCATION LAST TUESDAY. I HAD AN APPOINTMENT SCHEDULED FOR TWO IN THE AFTERNOON BUT WAS NOT SEEN UNTIL NEARLY FOUR, WITH NO EXPLANATION OR APOLOGY FROM ANY OF THE STAFF. WHEN I FINALLY SPOKE WITH A REPRESENTATIVE, I WAS TOLD THAT THE SYSTEM HAD DOUBLE BOOKED MY SLOT AND THAT THERE WAS NOTHING THEY COULD DO ABOUT THE WAIT. I FOUND THIS COMPLETELY UNACCEPTABLE GIVEN THAT I TOOK TIME OFF WORK SPECIFICALLY FOR THIS APPOINTMENT. TO MAKE MATTERS WORSE, WHEN THE SERVICE WAS FINALLY PERFORMED, IT WAS RUSHED AND INCOMPLETE. I HAD TO RETURN THE FOLLOWING DAY TO HAVE THE REMAINING WORK FINISHED, WHICH MEANT TAKING ADDITIONAL TIME OFF THAT I HAD NOT PLANNED FOR. I HAVE BEEN A LOYAL CUSTOMER FOR OVER FIVE YEARS AND HAVE ALWAYS RECOMMENDED YOUR BUSINESS TO FRIENDS AND FAMILY, BUT THIS EXPERIENCE HAS SERIOUSLY SHAKEN MY CONFIDENCE. I WOULD APPRECIATE A DIRECT RESPONSE EXPLAINING WHAT HAPPENED AND WHAT YOU INTEND TO DO TO MAKE THIS RIGHT, INCLUDING WHETHER I WILL BE COMPENSATED FOR THE EXTRA TIME I HAD TO SPEND DEALING WITH THIS ISSUE. PLEASE RESPOND WITHIN FIVE BUSINESS DAYS SO WE CAN RESOLVE THIS MATTER PROMPTLY. THANK YOU FOR YOUR ATTENTION TO THIS COMPLAINT.";

/** The headline demonstration fixture: five independent, non-repeating,
 *  realistic "accidental caps-lock" passages (support ticket, forum post,
 *  email, product review, chat message). */
export const STENTOR_CAPS_COMBO = [
  STENTOR_CAPS_SUPPORT, STENTOR_CAPS_FORUM, STENTOR_CAPS_EMAIL, STENTOR_CAPS_REVIEW, STENTOR_CAPS_CHAT,
].join('\n\n---\n\n');
