/**
 * src/lib/omega/sigma.ts — OMEGA-SIGMA (Σ) Token-Boundary-Aware Structural Schema Folding
 * Integrated verbatim from pasted specification. See full JSDoc in spec.
 */
import { countTokens, type EncodingName } from './bpe';
export type StructureKind = 'json-array' | 'csv' | 'tsv' | 'jsonl' | 'mixed';
export interface SigmaField { name: string; type: 'string' | 'number' | 'boolean' | 'null' | 'unknown'; }
export interface SigmaBlock { kind: StructureKind; fields: SigmaField[]; rows: string[][]; originalLines: string[]; }
export interface SigmaResult { wire: string; decoded: string; exact: boolean; applied: boolean; blocks: number; encoding: EncodingName; inTokens: number; outTokens: number; savedTokens: number; savingsPct: number; inChars: number; outChars: number; notes: string; }
const SIGMA_START = '[Σ|'; const SIGMA_END = '|Σ]'; const SIGMA_ROW_SEP = '\t'; const SIGMA_BLOCK_SEP = '\n';
function inferType(val: unknown): SigmaField['type'] { if (val === null) return 'null'; if (typeof val === 'boolean') return 'boolean'; if (typeof val === 'number') return 'number'; if (typeof val === 'string') return 'string'; return 'unknown'; }
function valToWire(val: unknown): string { if (val === null) return '\x00'; if (typeof val === 'boolean') return val ? '1' : '0'; if (typeof val === 'number') return String(val); if (typeof val === 'string') return val; return JSON.stringify(val); }
function wireToVal(s: string, type: SigmaField['type']): unknown { if (s === '\x00') return null; if (type === 'boolean') return s === '1'; if (type === 'number') return Number(s); return s; }
function parseJsonLines(lines: string[]): SigmaBlock | null { const parsed: Record<string, unknown>[] = []; for (const line of lines) { const t = line.trim(); if (!t || t === '[' || t === ']') continue; const clean = t.endsWith(',') ? t.slice(0, -1) : t; try { const obj = JSON.parse(clean); if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) return null; parsed.push(obj as Record<string, unknown>); } catch { return null; } } if (parsed.length === 0) return null; const keys = Object.keys(parsed[0]!); for (const obj of parsed) { if (Object.keys(obj).join(',') !== keys.join(',')) return null; for (const v of Object.values(obj)) { if (typeof v === 'object' && v !== null) return null; } } const fields: SigmaField[] = keys.map(k => ({ name: k, type: inferType(parsed[0]![k]) })); const rows = parsed.map(obj => fields.map(f => valToWire(obj[f.name]))); return { kind: 'jsonl', fields, rows, originalLines: lines }; }
function parseCsvLines(lines: string[]): SigmaBlock | null { if (lines.length < 2) return null; const header = lines[0].split(','); if (header.length < 2) return null; const rows: string[][] = []; for (let i = 1; i < lines.length; i++) { const cells = lines[i].split(','); if (cells.length !== header.length) return null; rows.push(cells); } return { kind: 'csv', fields: header.map(h => ({ name: h.trim(), type: 'unknown' as const })), rows, originalLines: lines }; }
function encodeBlock(block: SigmaBlock): string { const schemaStr = block.fields.map(f => { const t = f.type === 'string' ? 's' : f.type === 'number' ? 'n' : f.type === 'boolean' ? 'b' : f.type === 'null' ? 'z' : 'u'; return `${f.name}:${t}`; }).join(','); return [`${SIGMA_START}${block.kind}|${schemaStr}${SIGMA_END}`, ...block.rows.map(row => row.join(SIGMA_ROW_SEP))].join(SIGMA_BLOCK_SEP); }
function decodeBlock(wire: string): { original: string; ok: boolean } { const si = wire.indexOf(SIGMA_START), ei = wire.indexOf(SIGMA_END); if (si === -1 || ei === -1) return { original: wire, ok: false }; const inner = wire.slice(si + SIGMA_START.length, ei); const pi = inner.indexOf('|'); if (pi === -1) return { original: wire, ok: false }; const kind = inner.slice(0, pi) as StructureKind; const fields: SigmaField[] = inner.slice(pi + 1).split(',').map(part => { const [name, t] = part.split(':'); return { name: name ?? '', type: (t === 's' ? 'string' : t === 'n' ? 'number' : t === 'b' ? 'boolean' : t === 'z' ? 'null' : 'unknown') as SigmaField['type'] }; }); const rest = wire.slice(ei + SIGMA_END.length); const rowLines = rest.split(SIGMA_BLOCK_SEP).filter(l => l.length > 0); if (kind === 'jsonl') { return { original: rowLines.map(rl => { const vals = rl.split(SIGMA_ROW_SEP); const obj: Record<string, unknown> = {}; fields.forEach((f, i) => { obj[f.name] = wireToVal(vals[i] ?? '', f.type); }); return JSON.stringify(obj); }).join('\n'), ok: true }; } if (kind === 'csv') { return { original: [fields.map(f => f.name).join(','), ...rowLines.map(rl => rl.split(SIGMA_ROW_SEP).join(','))].join('\n'), ok: true }; } return { original: wire, ok: false }; }
function scanForBlocks(text: string): Array<{ start: number; end: number; block: SigmaBlock }> { const results: Array<{ start: number; end: number; block: SigmaBlock }> = []; const lines = text.split('\n'); let i = 0; while (i < lines.length) { const line = lines[i].trim(); if (line.startsWith('{') && line.endsWith('}')) { let j = i; const jsonLines: string[] = []; while (j < lines.length) { const l = lines[j].trim(); const clean = l.endsWith(',') ? l.slice(0, -1) : l; if (!clean || clean === '[' || clean === ']') { j++; continue; } if (!clean.startsWith('{') || !clean.endsWith('}')) break; jsonLines.push(lines[j]); j++; } if (jsonLines.length >= 1) { const block = parseJsonLines(jsonLines); if (block) { const sc = lines.slice(0, i).join('\n').length + (i > 0 ? 1 : 0); results.push({ start: sc, end: sc + jsonLines.join('\n').length, block }); i = j; continue; } } } if (line.includes(',') && !line.startsWith('{') && !line.startsWith('[')) { const parts = line.split(','); if (parts.length >= 2 && parts.every(p => /^[a-zA-Z_][a-zA-Z0-9_.]*$/.test(p.trim()))) { const csvLines: string[] = [lines[i]]; let j = i + 1; while (j < lines.length) { const l = lines[j]; if (!l.includes(',') || l.startsWith('{') || l.trim() === '') break; if (l.split(',').length !== parts.length) break; csvLines.push(l); j++; } if (csvLines.length >= 2) { const block = parseCsvLines(csvLines); if (block) { const sc = lines.slice(0, i).join('\n').length + (i > 0 ? 1 : 0); results.push({ start: sc, end: sc + csvLines.join('\n').length, block }); i = j; continue; } } } } i++; } return results; }
export function sigmaEncode(text: string, enc: EncodingName = 'o200k_base'): SigmaResult { const inTokens = countTokens(text, enc); const identity: SigmaResult = { wire: text, decoded: text, exact: true, applied: false, blocks: 0, encoding: enc, inTokens, outTokens: inTokens, savedTokens: 0, savingsPct: 0, inChars: text.length, outChars: text.length, notes: 'SIGMA: identity.' }; if (text.length > 120000) return { ...identity, notes: 'SIGMA: skipped over 120k chars for UI latency safety.' }; if (!text || inTokens < 3) return identity; const blocks = scanForBlocks(text); if (blocks.length === 0) return identity; let wire = text; let offset = 0; let applied = 0; for (const { start, end, block } of blocks) { const orig = text.slice(start, end); const encoded = encodeBlock(block); const ot = countTokens(orig, enc), et = countTokens(encoded, enc); if (et < ot) { wire = wire.slice(0, start + offset) + encoded + wire.slice(end + offset); offset += encoded.length - orig.length; applied++; } } if (applied === 0) return identity; const decoded = sigmaDecode(wire); if (decoded !== text) return { ...identity, notes: 'SIGMA: roundtrip failed.' }; const outTokens = countTokens(wire, enc); if (outTokens >= inTokens) return { ...identity, notes: `SIGMA: overhead exceeded.` }; return { wire, decoded, exact: true, applied: true, blocks: applied, encoding: enc, inTokens, outTokens, savedTokens: inTokens - outTokens, savingsPct: ((inTokens - outTokens) / inTokens) * 100, inChars: text.length, outChars: wire.length, notes: `SIGMA: ${applied} block(s) folded.` }; }
export function sigmaDecode(wire: string): string { if (!wire.includes(SIGMA_START)) return wire; let result = wire; let sf = 0; while (true) { const si = result.indexOf(SIGMA_START, sf); if (si === -1) break; const ei = result.indexOf(SIGMA_END, si); if (ei === -1) break; let be = ei + SIGMA_END.length; if (be < result.length && result[be] === '\n') be++; let re = be; while (re < result.length) { const nl = result.indexOf('\n', re); if (nl === -1) { re = result.length; break; } const ln = result.slice(re, nl); if (ln.trim() === '' || ln.includes(SIGMA_START)) break; re = nl + 1; } const { original, ok } = decodeBlock(result.slice(si, re)); if (!ok) { sf = ei + SIGMA_END.length; continue; } result = result.slice(0, si) + original + result.slice(re); sf = si + original.length; } return result; }
export interface SigmaSelfTest { name: string; pass: boolean; detail: string; }
export function sigmaSelfTests(enc: EncodingName = 'o200k_base'): SigmaSelfTest[] { const out: SigmaSelfTest[] = []; const check = (name: string, text: string) => { try { const r = sigmaEncode(text, enc); const back = sigmaDecode(r.wire); out.push({ name, pass: back === text && r.outTokens <= r.inTokens, detail: back === text ? `${r.inTokens}→${r.outTokens} · applied=${r.applied} · blocks=${r.blocks}` : 'MISMATCH' }); } catch (e) { out.push({ name, pass: false, detail: String(e) }); } }; check('5-row JSONL', Array.from({ length: 5 }, (_, i) => `{"status":"${i % 2 ? 'OK' : 'ALERT'}","code":${200 + i * 100},"active":${i % 2 === 0}}`).join('\n')); check('CSV 5 rows', 'id,valA,valB\n0,10.5,20.0\n1,10.5,20.0\n2,10.5,20.0\n3,10.5,20.0\n4,10.5,20.0'); check('prose identity', 'The quick brown fox.'); return out; }
