/**
 * src/lib/omega/strand-book.ts — GENERATED, DO NOT EDIT BY HAND.
 *
 * STRAND-SB1 static phrase book. Mined offline by bench/mine-strand.ts from
 * bench/train/** ONLY (a corpus disjoint from every evaluation fixture and
 * from bench/holdout/**). Frozen and version-pinned: the runtime encoder never
 * mines, so the book cannot absorb anything from the document it compresses.
 *
 * Order is part of the wire contract: phrase i binds to static glyph i.
 * Regenerate with:
 *   npx esbuild bench/mine-strand.ts --bundle --platform=node --format=esm \
 *     --alias:@=./src --outfile=/tmp/mine.mjs && node /tmp/mine.mjs > src/lib/omega/strand-book.ts
 */

export const STRAND_BOOK_VERSION = 'SB1';

export const STRAND_BOOK_O200K: readonly string[] = [
 "\": {\n        \"types\": \"./",
 "         *",
 "\",\n    \"",
 " | undefined;\n       ",
 "?: string | undefined;\n       ",
 "\",\n        \"default\": \"./",
 "\": {\n      \"import\": {\n        \"types",
 " {\n      \"import\": {\n        \"types\":",
 "      \"import\": {\n        \"types\": \"./",
 ".js\"\n      },\n      \"require\": {\n       ",
 "\"\n      },\n      \"require\": {\n        \"",
 "      },\n      \"require\": {\n        \"types",
 " },\n      \"require\": {\n        \"types\":",
 "      \"require\": {\n        \"types\": \"./",
 ".cjs\"\n      },\n      \"types\": \"./",
 "\"?: string | undefined;\n       ",
 "?: string | undefined;\n        \"",
 ".d.cts\",\n        \"default\": \"./",
 "\"?: string | undefined;\n        \"",
 ".d.ts\",\n        \"default\": \"./",
 ".d.ts\",\n      \"default\": \"./",
 "\n         *",
 ".js\"\n    },\n    \"./",
 ";\n        /**\n         *",
 "\": {\n      \"optional\": true\n    },\n",
 " {\n      \"optional\": true\n    },\n   ",
 " * @since v",
 "         *\n         *",
 "     *\n     *",
 "         * @since v",
 ".0",
 "-sqlite",
 "https://github.com",
 "         */\n       ",
 "\n         */\n       ",
 "     *  ",
 "\": \"0.28.2\",\n    \"@",
 " \"0.28.2\",\n    \"@es",
 "0.28.2\",\n    \"@esbuild",
 "\"\n  },\n  \"",
 "             *",
 " * @since v0.",
 ".0\n         */\n       ",
 ".\n         *",
 "](https://github.com",
 ".\n         * @",
 "      \"optional\": true\n    },\n    \"",
 ".0\",\n   ",
 "\": \"./bun-sql",
 ".0\",\n    \"",
 " | undefined;\n        /**\n         *",
 "     *\n     * ```js\n     *",
 ".\n         *\n         *",
 ".\n         * @since v",
 "https://github.com/dotenv",
 "64\": \"0.28.2\",\n   ",
 "      \"optional\": true\n    },\n    \"@",
 ": number;\n       ",
 ";\n            /**\n             *",
 "         * @since v0.",
 ": number;\n        /** Instructs OpenSSL",
 "\",\n  \"",
 "\": {\n        \"types\": \"./gel",
 "](https://github.com/dotenv",
 "https://github.com/dotenv-org/examples/tree",
 "://github.com/dotenv-org/examples/tree/master",
 "github.com/dotenv-org/examples/tree/master/",
 ".com/dotenv-org/examples/tree/master/usage",
 "/dotenv-org/examples/tree/master/usage/d",
 "otenv-org/examples/tree/master/usage/dot",
 "env-org/examples/tree/master/usage/dotenv",
 " number;\n        /** Instructs OpenSSL to",
 ".js\",\n    \"",
 ",\n     *  ",
 "\": {\n    \"",
 "\": \"./expo-sqlite",
 "\": \"^",
 "\"?: string | undefined;\n        \"access-control",
 "\": \"./better-sqlite3",
 " \"types\": \"./bun-sql",
 " \"default\": \"./bun-sql",
 "\": \"./durable-sqlite",
 "\": {\n        \"types\": \"./bun-sql",
 ".0.",
 " * @since v0.1.",
 " `urlObject",
 ".d.ts\",\n    \"",
 " \"default\": \"./gel",
 "\",\n        \"default\": \"./gel",
 "\": \"./gel-core",
 "\",\n        \"default\": \"./bun-sql",
 ".js\",\n      \"",
 " from 'node:",
 ".0.0",
 ".\n     *\n     *",
 "?: string | string[] | undefined;\n       ",
 "         * ```js\n         *",
 "         *\n         * ```js\n         *",
 " appended to `result`.\n     *",
 "\": \"./bun-sqlite",
 "\": {\n        \"types\": \"./gel-core",
 "</details>\n<details><summary>",
 "         *\n         * ```js\n         * import",
 "?: boolean | undefined;\n",
 " the `",
 "         *  ",
 ".js\",\n      \"default\": \"./",
 ".\n         * @since v0.",
 "         * ```js\n         * import {",
 "\": {\n      \"react-server\": \"./",
 "](https://github.com/dotenv-org/examples",
 " } from 'node:",
 "     *\n     * ```js\n     * import",
 "             *\n             *",
 "' --env '",
 " \"import\": {\n        \"types\": \"./gel",
 "\": \"^1.",
 "-sqlite/migrator",
 " \"default\": \"./gel-core",
 " \"types\": \"./expo-sqlite",
 " \"default\": \"./expo-sqlite",
 "\"?: string | undefined;\n        \"content",
 ".react-server.js\",\n      \"default\": \"./",
 " * The",
 "?: number | undefined;\n       ",
 ": number;\n        const",
 "https://github.com/dotenvx/dot",
 "://github.com/dotenvx/dotenv",
 "github.com/dotenvx/dotenvx",
 "?: string | string[] | undefined;\n        \"",
 " *\n         * ```js\n         * import {",
 "         * @since v0.1.90",
 " * @since v0.1.90\n",
 " @since v0.1.90\n        ",
 " \"require\": {\n        \"types\": \"./gel",
 ".d.cts\",\n        \"default\": \"./gel",
 "js\"\n      },\n      \"types\": \"./gel",
 "             * @",
 "     * //",
 " is appended to `result`.\n     *",
 "\",\n        \"default\": \"./gel-core",
 ";\n    }\n   ",
 ".\n         */\n       ",
 "n,\n     *  ",
 "\"?: string | undefined;\n        \"sec",
 "` is appended to `result`.\n     *",
 " \"types\": \"./better-sqlite3",
 " \"default\": \"./better-sqlite3",
 " \"types\": \"./durable-sqlite",
 " \"default\": \"./durable-sqlite",
 " | null | undefined;\n       ",
 "?: boolean | undefined;\n       ",
 " * The `",
 "             */\n           ",
 ".\n             *\n             *",
 "     * ```\n     * @since v",
 "?: string | null | undefined;\n       ",
 "```\n\n</details>\n<details><summary>",
 "](https://github.com/dotenvx/d",
 "pt-tokenizer",
 "    /**\n     *",
 ";\n        /**\n         * The",
 " * @see [source](https://github.com",
 " @see [source](https://github.com/node",
 "see [source](https://github.com/nodejs",
 " [source](https://github.com/nodejs/node",
 "source](https://github.com/nodejs/node/blob",
 "](https://github.com/nodejs/node/blob/v",
 "https://github.com/nodejs/node/blob/v22",
 "://github.com/nodejs/node/blob/v22.x",
 "github.com/nodejs/node/blob/v22.x/lib",
 " to `result`.\n     * * Otherwise, if",
 "\",\n    \"@esbuild/linux",
 "\": {\n        \"types\": \"./expo-sql",
 " {\n        \"types\": \"./expo-sqlite",
 "\",\n        \"default\": \"./expo-sqlite",
 "?: number | undefined;\n        /**\n         *",
 " * @param",
 " */\n        const SSL_OP",
 ".d.ts\",\n        \"default\": \"./gel",
 ".d.ts\",\n      \"default\": \"./gel",
 "     * ```\n     *\n     *",
 "             * @since v",
 " appended to `result`.\n     * *",
 "-sqlite/driver",
 " \"types\": \"./bun-sqlite",
 " \"default\": \"./bun-sqlite",
 " [dotenvx](https://github.com/dot",
 "dotenvx](https://github.com/dotenv",
 "x](https://github.com/dotenvx",
 " * @since v10.10.0\n",
 "         * @default",
 ".\n             * @",
 "  \"repository\": {\n    \"type\": \"",
 " \"repository\": {\n    \"type\": \"git",
 "repository\": {\n    \"type\": \"git\",\n",
 "\": {\n    \"type\": \"git\",\n   ",
 " {\n    \"type\": \"git\",\n    \"",
 "    \"type\": \"git\",\n    \"url",
 " \"type\": \"git\",\n    \"url\":",
 "type\": \"git\",\n    \"url\": \"",
 ".28.2\",\n    \"@esbuild/linux",
 " from 'gpt-tokenizer",
 " | undefined;\n    }\n   ",
 " boolean;\n        /**\n         *",
 ".\n         * @default",
 "?: boolean | undefined;\n        /**\n         *",
 "            /**\n             * The",
 ".0\n             */\n           ",
 ";\n            /**\n             * The",
 " is not `undefined` and is not a",
 " an `Error` is thrown.\n     *",
 "             * @throws {TypeError} if",
 "\": \"https://github.com",
 "/bin/esbuild\": \"",
 "64/bin/esbuild\": \"",
 " from \"node:",
 "         * ```\n         * @since v",
 "https://img.shields.io",
 ". */\n        const SSL_OP",
 ".3.",
 " * If the",
 ".com/dotenvx/dotenvx)",
 ": Mon, 10 Oct 2011 ",
 " Mon, 10 Oct 2011 23",
 ", 10 Oct 2011 23:",
 " 10 Oct 2011 23:24",
 "10 Oct 2011 23:24:",
 " Oct 2011 23:24:11",
 " 2011 23:24:11 GMT",
 "         * @since v10.10.0",
 " @since v10.10.0\n        ",
 "since v10.10.0\n         */\n",
 " v10.10.0\n         */\n       ",
 "?: string | undefined;\n        \"access-control-",
 " string | undefined;\n        \"access-control-allow",
 "\"?: string | undefined;\n        \"sec-web",
 "?: string | undefined;\n        \"sec-websocket",
 "\"?: string | string[] | undefined;\n       ",
 " } from 'node:events';\n",
 " EventEmitter } from 'node:events';\n",
 ":\n     *\n     * ```js\n     *",
 ".\n         * @since v0.1.",
 "         * @return The socket itself.\n         */\n",
 " * @return The socket itself.\n         */\n       ",
 " value of `urlObject",
 "`.\n     * * Otherwise, if `urlObject",
 "` is not `undefined` and is not a",
 " is not `undefined` and is not a string",
 " string, an `Error` is thrown.\n    ",
 ", an `Error` is thrown.\n     *",
 " an `Error` is thrown.\n     * *",
 " is appended to `result`.\n     *    *",
 " appended to `result`.\n     * * Otherwise,",
 ".\n             * @throws {TypeError} if",
 ".0\",\n    \"@",
 "  \"license\": \"MIT\",\n  \"",
 "-arm64\": \"0.28.2\",\n",
 "\": \"./d1",
 "\": \"./gel-core/",
 ".js\"\n    },\n    \"./gel",
 "igrator\": {\n      \"import\": {\n       ",
 "ator\": {\n      \"import\": {\n        \"",
 "igrator.d.ts\",\n        \"default\": \"./",
 "igrator.js\"\n      },\n      \"require\":",
 "ator.js\"\n      },\n      \"require\": {\n",
 "igrator.d.cts\",\n        \"default\":",
 "ator.d.cts\",\n        \"default\": \"./",
 "igrator.cjs\"\n      },\n      \"types",
 "ator.cjs\"\n      },\n      \"types\":",
 "igrator.d.ts\",\n      \"default\": \"./",
 "\": {\n        \"types\": \"./better-sql",
 " {\n        \"types\": \"./better-sqlite",
 "        \"types\": \"./better-sqlite3",
 "\",\n        \"default\": \"./better-sqlite",
 "        \"default\": \"./better-sqlite3",
 "/index.js\"\n      },\n      \"require\": {\n",
 "/index.d.cts\",\n        \"default\": \"./",
 "/index.cjs\"\n      },\n      \"types\":",
 " \"import\": {\n        \"types\": \"./bun",
 "import\": {\n        \"types\": \"./bun-s",
 ".d.ts\",\n        \"default\": \"./bun-s",
 ".ts\",\n        \"default\": \"./bun-sql",
 " \"require\": {\n        \"types\": \"./bun",
 "require\": {\n        \"types\": \"./bun-s",
 ".d.cts\",\n        \"default\": \"./bun",
 ".cts\",\n        \"default\": \"./bun-s",
 "js\"\n      },\n      \"types\": \"./bun",
 "\"\n      },\n      \"types\": \"./bun-s",
 "      },\n      \"types\": \"./bun-sql",
 ".d.ts\",\n      \"default\": \"./bun-s",
 ".ts\",\n      \"default\": \"./bun-sql",
 " {\n        \"types\": \"./bun-sqlite",
 "\",\n        \"default\": \"./bun-sqlite",
 "\": {\n        \"types\": \"./durable-s",
 " {\n        \"types\": \"./durable-sql",
 "        \"types\": \"./durable-sqlite",
 "\",\n        \"default\": \"./durable-sql",
 "        \"default\": \"./durable-sqlite",
 "import\": {\n        \"types\": \"./gel-core",
 "\": \"16.3.5\",\n    \"@",
 " => void): this;\n       ",
 " | undefined;\n        /**\n         * If",
 ".\n             * @since v",
 " * @since v0.9.",
 " } from 'node:events';\n        ",
 " * If the `urlObject",
 "/migrator.d.ts\",\n",
 ".1\",\n   ",
 " } from \"node:",
 " {\n        /**\n         *",
 ".1\",\n    \"",
 " of the",
 ": number;\n        const ENGINE_METHOD",
 ".0.0\",\n    \"",
 "\n *",
 ".0\n     */\n   ",
 ";\n        /**\n         * Returns",
 " this;\n        /**\n         *",
 " string;\n            /**\n             *",
 "</summary><br>\n\n",
 " } = await import('node:crypto');\n",
 "\"\n  ],\n  \"",
 "    \"url\": \"https://github.com",
 "      \"require\": \"./",
 "-x64\": \"0.28.2",
 "/index.d.ts\",\n        \"default\": \"./",
 "/index.d.ts\",\n      \"default\": \"./",
 ".js\"\n    },\n    \"./bun-sql",
 "\": {\n        \"types\": \"./d1",
 "Use [dotenvx](https://github.com/d",
 " {\n     *  ",
 "         */\n        readonly",
 "        /**\n         * Returns `true` if the",
 " /**\n         * Returns `true` if the `",
 "         * Returns `true` if the `fs",
 " * Returns `true` if the `fs.Dir",
 " Returns `true` if the `fs.Dirent",
 " `true` if the `fs.Dirent`",
 "true` if the `fs.Dirent` object",
 "` if the `fs.Dirent` object describes",
 " if the `fs.Dirent` object describes a",
 ".\n         * @since v10.10.",
 "10.10.0\n         */\n        is",
 "?: string | undefined;\n        \"if",
 " * ```\n * @see [source](https://",
 " ```\n * @see [source](https://github",
 " | undefined;\n        /**\n         * If set to",
 " *   console.log",
 ".\n         *\n         * ```js\n         *",
 ", EventEmitter } from 'node:events';\n",
 " EventEmitter } from 'node:events';\n        ",
 ";\n        /** Instructs OpenSSL to turn",
 "since v0.1.90\n         */\n",
 " v0.1.90\n         */\n       ",
 ".\n     *\n     * ```js\n     *",
 " is not a string.\n             */\n           ",
 "             * @throws {TypeError} if `",
 " * @throws {TypeError} if `path",
 " @throws {TypeError} if `path`",
 "  \"engines\": {\n    \"node\":",
 "  \"exports\": {\n    \".\": {\n     ",
 " \"exports\": {\n    \".\": {\n      \"",
 "-x64\": \"0.28.2\",\n",
 ".js\",\n      \"import\": \"./dist",
 "-sqlite/session",
 "/driver\": {\n      \"import\": {\n       ",
 "driver\": {\n      \"import\": {\n        \"",
 "/driver.d.ts\",\n        \"default\": \"./",
 "/driver.js\"\n      },\n      \"require\":",
 "driver.js\"\n      },\n      \"require\": {\n",
 "/driver.d.cts\",\n        \"default\":",
 "driver.d.cts\",\n        \"default\": \"./",
 "/driver.cjs\"\n      },\n      \"types",
 "driver.cjs\"\n      },\n      \"types\":",
 "/driver.d.ts\",\n      \"default\": \"./",
 "/migrator\": {\n      \"import\": {\n",
 "/migrator.d.ts\",\n        \"default\":",
 "/migrator.js\"\n      },\n      \"require",
 "/migrator.d.cts\",\n        \"default",
 "/migrator.cjs\"\n      },\n      \"",
 "/migrator.d.ts\",\n      \"default\":",
 "/session\": {\n      \"import\": {\n        \"",
 "/session.js\"\n      },\n      \"require\": {\n",
 "/session.d.cts\",\n        \"default\": \"./",
 "/session.cjs\"\n      },\n      \"types\":",
 ".d.ts\",\n        \"default\": \"./gel-core",
 "require\": {\n        \"types\": \"./gel-core",
 ".cts\",\n        \"default\": \"./gel-core",
 "\"\n      },\n      \"types\": \"./gel-core",
 ".d.ts\",\n      \"default\": \"./gel-core",
 " \"16.3.5\",\n    \"@next",
 "16.3.5\",\n    \"@next/s",
 ".3.5\",\n    \"@next/swc",
 "https://img.shields.io/npm",
 "/tailwindcss",
 ": T;\n       ",
 "\n         */\n        readonly",
 ": 131828905100",
 ".0\n     */\n    export",
 ".0\n             */\n            readonly",
 " {\n         *  ",
 "         * The `subprocess",
 "\": \"^0.",
 "\": {\n      \"require\": \"./",
 " \"default\": \"./d1",
 ".0, v",
 "https://www.npmjs.com/package",
 ".\n\nExample:\n\n```typescript\nimport {",
 " } from 'gpt-tokenizer'\n\n",
 " } from 'gpt-tokenizer'\n\nconst",
 "https://github.com/microsoft/TypeScript",
 " src=\"https://img.shields.io",
 ":\n *\n * ```js\n * import",
 "Ms: 1318289051000",
 " } from \"node:buffer\";\n    import",
 "\"?: string | undefined;\n        \"if",
 ".0\n             */\n            readonly readable",
 "         *\n         * const",
 " const ee = new EventEmitter();\n        ",
 ";\n    /**\n     *",
 "        /**\n         * The `subprocess",
 "     * * If the `urlObject",
 "'],\n     * //  ",
 ".3\",\n    \"",
 "\": {\n      \"require\": \"./dist",
 "igrator.js\"\n    },\n    \"./",
 "\",\n        \"default\": \"./d1",
 ".js\"\n    },\n    \"./gel-core",
 " \"./better-sqlite3/migrator",
 "/migrator.js\"\n    },\n    \"./",
 "/session.d.ts\",\n        \"default\": \"./",
 "/session.d.ts\",\n      \"default\": \"./",
 " \"./durable-sqlite/migrator",
 "`.\n         * @since v",
 "';\n         *\n         * const",
 " */\n        const SSL_OP_NO",
 "{\n  \"name\": \"",
 "\",\n  \"description\": \"",
 ")](https://",
 ")](https://www.npmjs.com/package",
 "\n```\n\n</details>\n<details><summary",
 "</summary><br>\n\nUse [dotenvx](",
 "summary><br>\n\nUse [dotenvx](https",
 "><br>\n\nUse [dotenvx](https://",
 "br>\n\nUse [dotenvx](https://github",
 ">\n\nUse [dotenvx](https://github.com",
 ")](https://github.com/dotenv-org",
 "- https://unpkg.com/gpt-tokenizer",
 " https://unpkg.com/gpt-tokenizer/dist",
 "](https://github.com/microsoft/TypeScript",
 ".\n     * @",
 " NonSharedBuffer } from \"node:buffer\";\n",
 "SharedBuffer } from \"node:buffer\";\n   ",
 "Buffer } from \"node:buffer\";\n    import",
 "2011 23:24:11 GMT,\n",
 "1 23:24:11 GMT,\n    ",
 " 23:24:11 GMT,\n     *",
 "23:24:11 GMT,\n     *  ",
 "time: Mon, 10 Oct 2011",
 "(): boolean;\n        /**\n         * Returns `true",
 " boolean;\n        /**\n         * Returns `true`",
 ";\n        /**\n         * Returns `true` if",
 " * @since v12.12.0\n",
 ")`](http://man7.org/linux/man-pages",
 "](http://man7.org/linux/man-pages/man",
 "-headers\"?: string | undefined;\n        \"",
 "headers\"?: string | undefined;\n        \"access",
 " undefined;\n        /**\n         * If set to `",
 ";\n        /**\n         * If set to `true",
 ":\n         *\n         * ```js\n         *",
 " } from 'node:events';\n         *\n        ",
 " from 'node:events';\n         *\n         *",
 ";\n        /** Instructs OpenSSL to disable",
 "        /** Instructs OpenSSL to turn off",
 " `result`.\n     * * Otherwise, if `",
 "result`.\n     * * Otherwise, if `url",
 " not `undefined` and is not a string,",
 " `undefined` and is not a string, an",
 "undefined` and is not a string, an `",
 "` and is not a string, an `Error",
 " and is not a string, an `Error`",
 " is not a string, an `Error` is",
 " not a string, an `Error` is thrown",
 " a string, an `Error` is thrown.\n",
 "` is appended to `result`.\n     *   ",
 " appended to `result`.\n     *    * The",
 " to `result`.\n     *    * The value",
 " `result`.\n     *    * The value of",
 "result`.\n     *    * The value of `",
 "`.\n     *    * The value of `url",
 "     *    * The value of `urlObject",
 "` is appended to `result`.\n     * *",
 " is appended to `result`.\n     * * Otherwise",
 "throws {TypeError} if `path` is",
 " {TypeError} if `path` is not",
 "TypeError} if `path` is not a",
 "Error} if `path` is not a string",
 "\": \">=",
 "  \"keywords\": [\n    \"",
 "  \"homepage\": \"https://",
 "\"\n  },\n  \"peerDependencies",
 " \"engines\": {\n    \"node\": \"",
 "engines\": {\n    \"node\": \">=",
 ".ts' --env 'outDir=dist'",
 "' --env 'outDir=dist' --",
 " --env 'outDir=dist' --env",
 "env 'outDir=dist' --env '",
 " 'outDir=dist' --env 'module",
 "outDir=dist' --env 'moduleTarget",
 "Dir=dist' --env 'moduleTarget=",
 "=dist' --env 'moduleTarget=umd",
 "dist' --env 'moduleTarget=umd'",
 "' --env 'moduleTarget=umd' --",
 " --env 'moduleTarget=umd' --env",
 "env 'moduleTarget=umd' --env '",
 " 'moduleTarget=umd' --env 'engine",
 "moduleTarget=umd' --env 'engineTarget",
 "Target=umd' --env 'engineTarget=",
 "=umd' --env 'engineTarget=web",
 "umd' --env 'engineTarget=web'",
 "' --env 'engineTarget=web' --",
 " --env 'engineTarget=web' --env",
 "env 'engineTarget=web' --env '",
 " 'engineTarget=web' --env 'code",
 "engineTarget=web' --env 'codeTarget",
 "Target=web' --env 'codeTarget=",
 "=web' --env 'codeTarget=es",
 "web' --env 'codeTarget=es202",
 "' --env 'codeTarget=es2022",
 " --env 'codeTarget=es2022'",
 "env 'codeTarget=es2022' --",
 " 'codeTarget=es2022' --env",
 "codeTarget=es2022' --env '",
 "Target=es2022' --env 'name",
 "=es2022' --env 'name=",
 "es2022' --env 'name=GPT",
 "2022' --env 'name=GPTTokenizer",
 ".mjs\"\n    },\n    \"./",
 "-sqlite/index",
 "/index.js\"\n    },\n    \"./",
 "-sqlite/migrator.d",
 " \"types\": \"./gel-core/",
 " \"default\": \"./gel-core/",
 "\": \"./better-sqlite3/migrator",
 "\": \"./durable-sqlite/migrator",
 "\": {\n        \"types\": \"./gel-core/",
 ";\n    }\n    interface",
 "         * @default ",
 ".0.0\n",
 " {@link",
 " | null;\n       ",
 "     *   //",
 "\": \"^2.",
 ".js)\n */\ndeclare module \"",
 "0n,\n     *  ",
 ".0\n         * @",
 " boolean;\n            /**\n             *",
 " the value of `urlObject",
 "     *    * If the",
 "\",\n  \"version\": \"",
 " will be",
 "/tailwindlabs/tailwindcss",
 "?: boolean | undefined;\n    }\n   ",
 "'\n     * ```\n     *\n     *",
 ".0\n     */\n    export function",
 " \"./better-sqlite3/driver",
 "/driver.js\"\n    },\n    \"./",
 " \"./bun-sqlite/migrator",
 " \"./durable-sqlite/driver",
 " \"./expo-sqlite/migrator",
 ".com/tailwindlabs/tailwindcss",
 "https://github.com/vercel/next.js",
 "`.\n         *\n         *",
 "(): this;\n        /**\n         *",
 "timeMs: 1318289051000",
 " | undefined;\n    }\n    interface",
 " boolean | undefined;\n        /**\n         * If",
 "             * @param",
 "         * @since v0.9.",
 ".2.",
 "         *   console.log",
 "\n         * @param",
 "         * ```\n         *\n         *",
 " = new EventEmitter();\n         *\n         *",
 ";\n        /**\n         * The `subprocess",
 ":\n     *    * If the",
 "     *    * If the `urlObject",
 "` is not a string.\n             */\n           ",
 "Dependencies\": {\n   ",
 "  \"scripts\": {\n    \"",
 "\",\n  \"exports\": {\n    \".\":",
 "  },\n  \"scripts\": {\n    \"",
 "\": \"beemo webpack --entry='./src",
 "\": \"./better-sqlite3/driver",
 "\": \"./bun-sqlite/migrator",
 "-sqlite/migrator.d.ts\",\n",
 "\": \"./durable-sqlite/driver",
 "\": \"./expo-sqlite/migrator",
 "\",\n        \"default\": \"./gel-core/",
 "1.0",
 " the child process",
 ",\n  decode,\n  isWithinTokenLimit,\n",
 "  decode,\n  isWithinTokenLimit,\n ",
 " from 'gpt-tokenizer/model/gpt-",
 "'\n\nconst text = 'Hello, world!'\nconst",
 ".3.0",
 ".\n     * @since v",
 " * @since v22.",
 "\" {\n    import { NonSharedBuffer } from",
 " {\n    import { NonSharedBuffer } from \"",
 "    import { NonSharedBuffer } from \"node",
 " import { NonSharedBuffer } from \"node:",
 " { NonSharedBuffer } from \"node:buffer",
 " } from \"node:buffer\";\n    import *",
 " from \"node:buffer\";\n    import * as",
 " \"node:buffer\";\n    import * as stream",
 " EventEmitter } from \"node:events\";\n   ",
 "Emitter } from \"node:events\";\n    import",
 "     * ```\n     * @since v0.",
 "         * @since v12.12.0",
 " @since v12.12.0\n        ",
 " * @since v14.3.0,",
 " @since v14.3.0, v",
 "since v14.3.0, v12",
 " v14.3.0, v12.",
 "14.3.0, v12.20",
 ".3.0, v12.20.",
 "3.0, v12.20.0",
 ".0, v12.20.0\n",
 ".\n         * @default ",
 " * @since v18.",
 "        /**\n         * If set to `true`,",
 "?: boolean | undefined;\n        /**\n         * If",
 "             * The `readable",
 "https://nodejs.org/docs/latest-v22.x",
 "://nodejs.org/docs/latest-v22.x/api",
 " * @since v0.9.4\n",
 "';\n         *\n         * const ee = new Event",
 "         *\n         * const ee = new EventEmitter",
 " *\n         * const ee = new EventEmitter();\n",
 "         * const ee = new EventEmitter();\n        ",
 " const ee = new EventEmitter();\n         *\n        ",
 " ee = new EventEmitter();\n         *\n         *",
 "     * });\n     * ```\n     * @since",
 " * });\n     * ```\n     * @since v",
 " * import { spawn } from 'node:child",
 " import { spawn } from 'node:child_process",
 " { spawn } from 'node:child_process';\n",
 "         * assert.strictEqual(subprocess.stdio[",
 ": string | null;\n       ",
 " *\n     * ```js\n     * import url",
 "     * ```js\n     * import url from",
 " * ```js\n     * import url from '",
 " ```js\n     * import url from 'node",
 "js\n     * import url from 'node:url",
 "\n     * import url from 'node:url';\n",
 "     * import url from 'node:url';\n    ",
 "             *\n             * @param",
 "} if `path` is not a string.\n",
 " if `path` is not a string.\n            ",
 " `path` is not a string.\n             */\n",
 "path` is not a string.\n             */\n           ",
 "'],\n     * //   [",
 "     *\n     * ```js\n     * util",
 " *\n     * ```js\n     * util.format",
 "\": \"^3.",
 "\": \"^1.0.",
 "  },\n  \"repository\": {\n    \"type",
 " },\n  \"repository\": {\n    \"type\":",
 "\": \"git\",\n    \"url\": \"git",
 "\"\n  },\n  \"peerDependencies\": {\n   ",
 "\",\n  \"exports\": {\n    \".\": {\n",
 "\": \"beemo webpack --entry='./src/",
 " \"beemo webpack --entry='./src/encoding",
 "\": {\n      \"react-server\": \"./server.react",
 " {\n      \"react-server\": \"./server.react-server",
 "      \"react-server\": \"./server.react-server.js",
 " \"react-server\": \"./server.react-server.js\",\n",
 "react-server\": \"./server.react-server.js\",\n     ",
 "-server\": \"./server.react-server.js\",\n      \"",
 "-sqlite/driver.d",
 ".js\"\n    },\n    \"./expo-sqlite",
 " \"import\": {\n        \"types\": \"./expo",
 "import\": {\n        \"types\": \"./expo-s",
 ".d.ts\",\n        \"default\": \"./expo-s",
 ".ts\",\n        \"default\": \"./expo-sql",
 " \"require\": {\n        \"types\": \"./expo",
 "require\": {\n        \"types\": \"./expo-s",
 ".d.cts\",\n        \"default\": \"./expo",
 ".cts\",\n        \"default\": \"./expo-s",
 "js\"\n      },\n      \"types\": \"./expo",
 "\"\n      },\n      \"types\": \"./expo-s",
 "      },\n      \"types\": \"./expo-sql",
 " },\n      \"types\": \"./expo-sqlite",
 ".d.ts\",\n      \"default\": \"./expo-s",
 ".ts\",\n      \"default\": \"./expo-sql",
 "\",\n      \"default\": \"./expo-sqlite",
 "](https://img.shields.io",
 "https://github.com/niieani",
 "](https://www.typescriptlang.org",
 "https://github.com/tailwind",
 "\";\n    import {",
 " the\n     *",
 " *     console.log",
 ".0\n         */\n        readonly",
 " | null;\n        /**\n         *",
 " () => void): this;\n       ",
 " * @since v0.5.",
 "         * @since v18.",
 "         * @default false\n        ",
 "'` event",
 ": boolean;\n            /**\n             *",
 "         * });\n         *\n         *",
 " of the `spkac`",
 ".\n     * @since v0.",
 " from 'node:child_process';\n        ",
 "): string;\n    /**\n     *",
 " string:\n     *    * If the",
 " string;\n            /**\n             * The",
 ".\n             *\n             * @param",
 "             *\n             * @param path",
 "): string;\n            /**\n             *",
 " string): string;\n            /**\n             *",
 "     * //   [0, '",
 "\",\n    \"./",
 "  \"files\": [\n    \"",
 ".0.3\",\n    \"",
 "  \"devDependencies\": {\n   ",
 "    \"./package.json\": \"./package.json",
 "  \"devDependencies\": {\n    \"@",
 "\",\n    \"@esbuild/win32",
 " \"./better-sqlite3/session",
 "/session.js\"\n    },\n    \"./",
 " \"./bun-sql/migrator",
 " \"./bun-sqlite/driver",
 " \"./durable-sqlite/session",
 " \"./expo-sqlite/driver",
 " \"./gel-core/foreign-keys",
 "0.10.0\",\n    \"@",
 "\": \"./better-sqlite3/index",
 "\": \"./better-sqlite3/session",
 "\": \"./bun-sql/migrator",
 "\": \"./bun-sqlite/driver",
 "-sqlite/driver.d.ts\",\n",
 "-sqlite/migrator.js\"\n",
 "\": \"./durable-sqlite/index",
 "\": \"./durable-sqlite/session",
 "\": \"./expo-sqlite/driver",
 "\": \"./gel-core/foreign-keys",
 ": string,",
 " src=\"https://img.shields.io/npm",
 " string;\n        /**\n         *",
 " from \"node:stream\";\n    import {",
 "         * @since v0.5.",
 " | undefined;\n        \"accept",
 "-encoding\"?: string | undefined;\n       ",
 "         * @default false\n         */\n       ",
 "\" | \"",
 "             *  ",
 ";\n            /**\n             * The `readable",
 "             *\n             * ```js\n             *",
 " => {\n         *  ",
 "         *\n         * The",
 "Options {\n        /**\n         *",
 "    /**\n     * The `",
 "        /**\n         * Returns the",
 "        /**\n         * ```js\n         *",
 "     *\n     * const",
 " `urlObject.search`",
 "\" {\n    import path = require(\"path",
 ": string): string;\n            /**\n             *",
 "'],\n     * //   [1, '",
 " `gpt-",
 " the\n         *",
 " the literal string `",
 "\",\n    \"build",
 ".js\",\n  \"",
 "\": \"^4.",
 "k_base",
 "         *    ",
 " to the",
 "/dotenvx/dotenvx) for",
 "://github.com/motdotla/dotenv",
 "https://github.com/niieani/gpt",
 "://github.com/niieani/gpt-token",
 "github.com/niieani/gpt-tokenizer",
 " 'gpt-tokenizer/model/gpt-4",
 "gpt-tokenizer/model/gpt-4o",
 " {\n  encode,\n  decode,\n  isWithin",
 "  encode,\n  decode,\n  isWithinToken",
 " encode,\n  decode,\n  isWithinTokenLimit",
 " decode,\n  isWithinTokenLimit,\n  //",
 ",\n  isWithinTokenLimit,\n  // etc",
 "  isWithinTokenLimit,\n  // etc...\n",
 " isWithinTokenLimit,\n  // etc...\n}",
 " } from 'gpt-tokenizer'\n\nconst text",
 " from 'gpt-tokenizer'\n\nconst text =",
 " 'gpt-tokenizer'\n\nconst text = '",
 "gpt-tokenizer'\n\nconst text = 'Hello",
 "pt-tokenizer'\n\nconst text = 'Hello,",
 "-tokenizer'\n\nconst text = 'Hello, world",
 "izer'\n\nconst text = 'Hello, world!'\n",
 "\"><img src=\"https://img.shields.io",
 "https://github.com/tailwindcss/tail",
 "://github.com/tailwindcss/tailwind",
 "github.com/tailwindcss/tailwindcss",
 ".\n *\n *",
 " *   const",
 "     *     console.log",
 ": string;\n        /**\n         *",
 "node:buffer\";\n    import * as stream from",
 ":buffer\";\n    import * as stream from \"",
 "buffer\";\n    import * as stream from \"node",
 "\";\n    import * as stream from \"node:",
 "    import * as stream from \"node:stream",
 " import * as stream from \"node:stream\";\n",
 " * as stream from \"node:stream\";\n   ",
 " as stream from \"node:stream\";\n    import",
 " stream from \"node:stream\";\n    import {"
];

export const STRAND_BOOK_CL100K: readonly string[] = [
 "\": {\n        \"types\": \"./",
 "         *",
 "\",\n    \"",
 " | undefined;\n       ",
 "?: string | undefined;\n       ",
 "\",\n        \"default\": \"./",
 "\": {\n      \"import\": {\n        \"types",
 " {\n      \"import\": {\n        \"types\":",
 "      \"import\": {\n        \"types\": \"./",
 ".js\"\n      },\n      \"require\": {\n       ",
 "\"\n      },\n      \"require\": {\n        \"",
 "      },\n      \"require\": {\n        \"types",
 " },\n      \"require\": {\n        \"types\":",
 "      \"require\": {\n        \"types\": \"./",
 ".cjs\"\n      },\n      \"types\": \"./",
 "\"?: string | undefined;\n       ",
 "?: string | undefined;\n        \"",
 ".d.cts\",\n        \"default\": \"./",
 "\"?: string | undefined;\n        \"",
 ".d.ts\",\n        \"default\": \"./",
 ".d.ts\",\n      \"default\": \"./",
 "\n         *",
 ".js\"\n    },\n    \"./",
 ";\n        /**\n         *",
 "\": {\n      \"optional\": true\n    },\n",
 " {\n      \"optional\": true\n    },\n   ",
 " * @since v",
 "         *\n         *",
 "     *\n     *",
 "         * @since v",
 ".0",
 "-sqlite",
 "https://github.com",
 "         */\n       ",
 "\n         */\n       ",
 "\": \"./bun-sql",
 "     *  ",
 "\": \"0.28.2\",\n    \"@",
 " \"0.28.2\",\n    \"@es",
 "0.28.2\",\n    \"@esbuild",
 "\"\n  },\n  \"",
 "             *",
 " * @since v0.",
 ".0\n         */\n       ",
 ".\n         *",
 "](https://github.com",
 ".\n         * @",
 "      \"optional\": true\n    },\n    \"",
 ".0\",\n   ",
 ".0\",\n    \"",
 " | undefined;\n        /**\n         *",
 "     *\n     * ```js\n     *",
 ".\n         *\n         *",
 ".\n         * @since v",
 "https://github.com/dotenv",
 "64\": \"0.28.2\",\n   ",
 "      \"optional\": true\n    },\n    \"@",
 ": number;\n       ",
 " \"types\": \"./bun-sql",
 " \"default\": \"./bun-sql",
 ";\n            /**\n             *",
 "         * @since v0.",
 "\",\n  \"",
 "\": {\n        \"types\": \"./gel",
 "](https://github.com/dotenv",
 "https://github.com/dotenv-org/examples/tree",
 "://github.com/dotenv-org/examples/tree/master",
 "github.com/dotenv-org/examples/tree/master/",
 ".com/dotenv-org/examples/tree/master/usage",
 "/dotenv-org/examples/tree/master/usage/d",
 "otenv-org/examples/tree/master/usage/dot",
 "env-org/examples/tree/master/usage/dotenv",
 ": number;\n        /** Instructs OpenSSL to",
 ".js\",\n    \"",
 ",\n     *  ",
 "\": {\n    \"",
 "\": \"./expo-sqlite",
 "\": \"^",
 "\"?: string | undefined;\n        \"access-control",
 "\": \"./better-sqlite3",
 "\": \"./bun-sqlite",
 "\": \"./durable-sqlite",
 "\": {\n        \"types\": \"./bun-s",
 " {\n        \"types\": \"./bun-sql",
 "\",\n        \"default\": \"./bun-sql",
 ".0.",
 " * @since v0.1.",
 " `urlObject",
 ".d.ts\",\n    \"",
 " \"default\": \"./gel",
 "\",\n        \"default\": \"./gel",
 "\": \"./gel-core",
 ".js\",\n      \"",
 " from 'node:",
 ".0.0",
 ".\n     *\n     *",
 "?: string | string[] | undefined;\n       ",
 "         * ```js\n         *",
 "         *\n         * ```js\n         *",
 " appended to `result`.\n     *",
 "\": {\n        \"types\": \"./gel-core",
 "         *\n         * ```js\n         * import",
 "?: boolean | undefined;\n",
 "         *  ",
 ".js\",\n      \"default\": \"./",
 " the `",
 ".\n         * @since v0.",
 "         * ```js\n         * import {",
 "\": {\n      \"react-server\": \"./",
 "\": {\n        \"types\": \"./d",
 "</details>\n<details><summary",
 "](https://github.com/dotenv-org/examples",
 " } from 'node:",
 "     *\n     * ```js\n     * import",
 "             *\n             *",
 "' --env '",
 " \"import\": {\n        \"types\": \"./gel",
 "\": \"^1.",
 "-sqlite/migrator",
 " \"default\": \"./gel-core",
 " \"types\": \"./expo-sqlite",
 " \"default\": \"./expo-sqlite",
 "\"?: string | undefined;\n        \"content",
 ".react-server.js\",\n      \"default\": \"./",
 " * The",
 "?: number | undefined;\n       ",
 ": number;\n        const",
 "https://github.com/dotenvx/dot",
 "://github.com/dotenvx/dotenv",
 "github.com/dotenvx/dotenvx",
 "?: string | string[] | undefined;\n        \"",
 " *\n         * ```js\n         * import {",
 "         * @since v0.1.90",
 " * @since v0.1.90\n",
 " @since v0.1.90\n        ",
 " \"require\": {\n        \"types\": \"./gel",
 ".d.cts\",\n        \"default\": \"./gel",
 "js\"\n      },\n      \"types\": \"./gel",
 "</details>\n<details><summary>",
 "             * @",
 "     * //",
 " is appended to `result`.\n     *",
 "\",\n        \"default\": \"./gel-core",
 ";\n    }\n   ",
 ".\n         */\n       ",
 "n,\n     *  ",
 "\"?: string | undefined;\n        \"sec",
 "` is appended to `result`.\n     *",
 " \"default\": \"./d",
 "\",\n        \"default\": \"./d",
 " \"types\": \"./better-sqlite3",
 " \"default\": \"./better-sqlite3",
 " \"types\": \"./bun-sqlite",
 " \"default\": \"./bun-sqlite",
 " \"types\": \"./durable-sqlite",
 " \"default\": \"./durable-sqlite",
 " | null | undefined;\n       ",
 "?: boolean | undefined;\n       ",
 " * The `",
 "             */\n           ",
 ".\n             *\n             *",
 "     * ```\n     * @since v",
 "?: string | null | undefined;\n       ",
 "](https://github.com/dotenvx/d",
 "pt-tokenizer",
 "    /**\n     *",
 ";\n        /**\n         * The",
 " * @see [source](https://github.com",
 " @see [source](https://github.com/node",
 "see [source](https://github.com/nodejs",
 " [source](https://github.com/nodejs/node",
 "source](https://github.com/nodejs/node/blob",
 "](https://github.com/nodejs/node/blob/v",
 "https://github.com/nodejs/node/blob/v22",
 "://github.com/nodejs/node/blob/v22.x",
 "github.com/nodejs/node/blob/v22.x/lib",
 " to `result`.\n     * * Otherwise, if",
 "\",\n    \"@esbuild/linux",
 "\": {\n        \"types\": \"./expo-sql",
 " {\n        \"types\": \"./expo-sqlite",
 "\",\n        \"default\": \"./expo-sqlite",
 "```\n\n</details>\n<details><summary",
 "?: number | undefined;\n        /**\n         *",
 " * @param",
 " */\n        const SSL_OP",
 ".d.ts\",\n        \"default\": \"./gel",
 ".d.ts\",\n      \"default\": \"./gel",
 "     * ```\n     *\n     *",
 "             * @since v",
 " appended to `result`.\n     * *",
 "-sqlite/driver",
 " [dotenvx](https://github.com/dot",
 "dotenvx](https://github.com/dotenv",
 "x](https://github.com/dotenvx",
 " * @since v10.10.0\n",
 "         * @default",
 ".\n             * @",
 "  \"repository\": {\n    \"type\": \"",
 " \"repository\": {\n    \"type\": \"git",
 "repository\": {\n    \"type\": \"git\",\n",
 "\": {\n    \"type\": \"git\",\n   ",
 " {\n    \"type\": \"git\",\n    \"",
 "    \"type\": \"git\",\n    \"url",
 " \"type\": \"git\",\n    \"url\":",
 "type\": \"git\",\n    \"url\": \"",
 ".28.2\",\n    \"@esbuild/linux",
 " from 'gpt-tokenizer",
 " | undefined;\n    }\n   ",
 " boolean;\n        /**\n         *",
 ".\n         * @default",
 "?: boolean | undefined;\n        /**\n         *",
 "            /**\n             * The",
 ".0\n             */\n           ",
 ";\n            /**\n             * The",
 " is not `undefined` and is not a",
 " an `Error` is thrown.\n     *",
 "\": \"https://github.com",
 "/bin/esbuild\": \"",
 "64/bin/esbuild\": \"",
 "         * ```\n         * @since v",
 "https://img.shields.io",
 " from \"node:",
 ". */\n        const SSL_OP",
 ".3.",
 " * If the",
 "```\n\n</details>\n<details><summary>",
 ".com/dotenvx/dotenvx)",
 ": Mon, 10 Oct 2011 ",
 " Mon, 10 Oct 2011 23",
 ", 10 Oct 2011 23:",
 " 10 Oct 2011 23:24",
 "10 Oct 2011 23:24:",
 " Oct 2011 23:24:11",
 " 2011 23:24:11 GMT",
 "         * @since v10.10.0",
 " @since v10.10.0\n        ",
 "since v10.10.0\n         */\n",
 " v10.10.0\n         */\n       ",
 "?: string | undefined;\n        \"access-control-",
 " string | undefined;\n        \"access-control-allow",
 "\"?: string | undefined;\n        \"sec-web",
 "?: string | undefined;\n        \"sec-websocket",
 "\"?: string | string[] | undefined;\n       ",
 " } from 'node:events';\n",
 ":\n     *\n     * ```js\n     *",
 ".\n         * @since v0.1.",
 "         * @return The socket itself.\n         */\n",
 " * @return The socket itself.\n         */\n       ",
 " value of `urlObject",
 "`.\n     * * Otherwise, if `urlObject",
 "` is not `undefined` and is not a",
 " is not `undefined` and is not a string",
 " string, an `Error` is thrown.\n    ",
 ", an `Error` is thrown.\n     *",
 " an `Error` is thrown.\n     * *",
 " is appended to `result`.\n     *    *",
 " appended to `result`.\n     * * Otherwise,",
 ".0\",\n    \"@",
 "  \"license\": \"MIT\",\n  \"",
 "-arm64\": \"0.28.2\",\n",
 "\": \"./d1",
 "\": \"./gel-core/",
 ".js\"\n    },\n    \"./gel",
 "igrator\": {\n      \"import\": {\n       ",
 "ator\": {\n      \"import\": {\n        \"",
 "igrator.d.ts\",\n        \"default\": \"./",
 "igrator.js\"\n      },\n      \"require\":",
 "ator.js\"\n      },\n      \"require\": {\n",
 "igrator.d.cts\",\n        \"default\":",
 "ator.d.cts\",\n        \"default\": \"./",
 "igrator.cjs\"\n      },\n      \"types",
 "ator.cjs\"\n      },\n      \"types\":",
 "igrator.d.ts\",\n      \"default\": \"./",
 "\": {\n        \"types\": \"./better-sql",
 " {\n        \"types\": \"./better-sqlite",
 "        \"types\": \"./better-sqlite3",
 "\",\n        \"default\": \"./better-sqlite",
 "        \"default\": \"./better-sqlite3",
 "/index.js\"\n      },\n      \"require\": {\n",
 "/index.d.cts\",\n        \"default\": \"./",
 "/index.cjs\"\n      },\n      \"types\":",
 ".js\"\n    },\n    \"./bun-sql",
 " \"import\": {\n        \"types\": \"./b",
 "import\": {\n        \"types\": \"./bun",
 ".d.ts\",\n        \"default\": \"./bun",
 ".ts\",\n        \"default\": \"./bun-s",
 " \"require\": {\n        \"types\": \"./b",
 "require\": {\n        \"types\": \"./bun",
 ".d.cts\",\n        \"default\": \"./b",
 ".cts\",\n        \"default\": \"./bun",
 "js\"\n      },\n      \"types\": \"./b",
 "\"\n      },\n      \"types\": \"./bun",
 "      },\n      \"types\": \"./bun-s",
 " },\n      \"types\": \"./bun-sql",
 ".d.ts\",\n      \"default\": \"./bun",
 ".ts\",\n      \"default\": \"./bun-s",
 "\",\n      \"default\": \"./bun-sql",
 "        \"types\": \"./bun-sqlite",
 "        \"default\": \"./bun-sqlite",
 " \"import\": {\n        \"types\": \"./d",
 " \"require\": {\n        \"types\": \"./d",
 ".d.cts\",\n        \"default\": \"./d",
 "js\"\n      },\n      \"types\": \"./d",
 "\": {\n        \"types\": \"./durable-s",
 " {\n        \"types\": \"./durable-sql",
 "        \"types\": \"./durable-sqlite",
 "\",\n        \"default\": \"./durable-sql",
 "        \"default\": \"./durable-sqlite",
 "import\": {\n        \"types\": \"./gel-core",
 "\": \"16.3.5\",\n    \"@",
 " => void): this;\n       ",
 " | undefined;\n        /**\n         * If",
 ".\n             * @since v",
 " * @since v0.9.",
 " } from 'node:events';\n        ",
 " * If the `urlObject",
 "             * @throws {TypeError} if",
 "/migrator.d.ts\",\n",
 ".1\",\n   ",
 " {\n        /**\n         *",
 ".1\",\n    \"",
 " of the",
 " } from \"node",
 ": number;\n        const ENGINE_METHOD",
 ".0.0\",\n    \"",
 "\n *",
 ".0\n     */\n   ",
 ";\n        /**\n         * Returns",
 " this;\n        /**\n         *",
 " string;\n            /**\n             *",
 "</summary><br>\n\n",
 " } from \"node:",
 " } = await import('node:crypto');\n",
 ".\n             * @throws {TypeError} if",
 "\"\n  ],\n  \"",
 "    \"url\": \"https://github.com",
 "      \"require\": \"./",
 "-x64\": \"0.28.2",
 "/index.d.ts\",\n        \"default\": \"./",
 "/index.d.ts\",\n      \"default\": \"./",
 "\": {\n        \"types\": \"./d1",
 ".d.ts\",\n        \"default\": \"./d",
 ".d.ts\",\n      \"default\": \"./d",
 "Use [dotenvx](https://github.com/d",
 " {\n     *  ",
 "         */\n        readonly",
 "        /**\n         * Returns `true` if the",
 " /**\n         * Returns `true` if the `",
 "         * Returns `true` if the `fs",
 " * Returns `true` if the `fs.D",
 " Returns `true` if the `fs.Dire",
 " `true` if the `fs.Dirent",
 "true` if the `fs.Dirent`",
 "` if the `fs.Dirent` object",
 " if the `fs.Dirent` object describes",
 " the `fs.Dirent` object describes a",
 ".\n         * @since v10.10.",
 "10.10.0\n         */\n        is",
 "?: string | undefined;\n        \"if",
 " * ```\n * @see [source](https://",
 " ```\n * @see [source](https://github",
 " | undefined;\n        /**\n         * If set to",
 " *   console.log",
 " EventEmitter } from 'node:events';\n",
 ".\n         *\n         * ```js\n         *",
 ", EventEmitter } from 'node:events';\n        ",
 " number;\n        /** Instructs OpenSSL to turn",
 "since v0.1.90\n         */\n",
 " v0.1.90\n         */\n       ",
 ".\n     *\n     * ```js\n     *",
 " is not a string.\n             */\n           ",
 "             * @throws {TypeError} if `path",
 " * @throws {TypeError} if `path`",
 "  \"engines\": {\n    \"node\":",
 "  \"exports\": {\n    \".\": {\n     ",
 " \"exports\": {\n    \".\": {\n      \"",
 "-x64\": \"0.28.2\",\n",
 ".js\",\n      \"import\": \"./dist",
 "-sqlite/session",
 "/driver\": {\n      \"import\": {\n       ",
 "river\": {\n      \"import\": {\n        \"",
 "/driver.d.ts\",\n        \"default\": \"./",
 "/driver.js\"\n      },\n      \"require\":",
 "river.js\"\n      },\n      \"require\": {\n",
 "/driver.d.cts\",\n        \"default\":",
 "river.d.cts\",\n        \"default\": \"./",
 "/driver.cjs\"\n      },\n      \"types",
 "river.cjs\"\n      },\n      \"types\":",
 "/driver.d.ts\",\n      \"default\": \"./",
 "/migrator\": {\n      \"import\": {\n",
 "/migrator.d.ts\",\n        \"default\":",
 "/migrator.js\"\n      },\n      \"require",
 "/migrator.d.cts\",\n        \"default",
 "/migrator.cjs\"\n      },\n      \"",
 "/migrator.d.ts\",\n      \"default\":",
 "/session\": {\n      \"import\": {\n        \"",
 "/session.js\"\n      },\n      \"require\": {\n",
 "/session.d.cts\",\n        \"default\": \"./",
 "/session.cjs\"\n      },\n      \"types\":",
 ".d.ts\",\n        \"default\": \"./gel-core",
 "require\": {\n        \"types\": \"./gel-core",
 ".cts\",\n        \"default\": \"./gel-core",
 "\"\n      },\n      \"types\": \"./gel-core",
 ".d.ts\",\n      \"default\": \"./gel-core",
 " \"16.3.5\",\n    \"@next",
 "16.3.5\",\n    \"@next/sw",
 ".3.5\",\n    \"@next/swc",
 "https://img.shields.io/npm",
 "/tailwindcss",
 ": T;\n       ",
 "\n         */\n        readonly",
 ": 131828905100",
 ".0\n     */\n    export",
 ".0\n             */\n            readonly",
 " {\n         *  ",
 "         * The `subprocess",
 "\": \"^0.",
 "\": {\n      \"require\": \"./",
 " \"default\": \"./d1",
 ".0, v",
 "https://www.npmjs.com/package",
 ".\n\nExample:\n\n```typescript\nimport {",
 " } from 'gpt-tokenizer'\n\n",
 " } from 'gpt-tokenizer'\n\nconst",
 "https://github.com/microsoft/TypeScript",
 " src=\"https://img.shields.io",
 ":\n *\n * ```js\n * import",
 "Ms: 1318289051000",
 " } from \"node:buffer\";\n    import",
 "\"?: string | undefined;\n        \"if",
 ".0\n             */\n            readonly readable",
 "         *\n         * const",
 ";\n    /**\n     *",
 "        /**\n         * The `subprocess",
 "     * * If the `urlObject",
 "'],\n     * //  ",
 ".3\",\n    \"",
 "\": {\n      \"require\": \"./dist",
 "igrator.js\"\n    },\n    \"./",
 "\",\n        \"default\": \"./d1",
 ".js\"\n    },\n    \"./gel-core",
 " \"./better-sqlite3/migrator",
 "/migrator.js\"\n    },\n    \"./",
 "/session.d.ts\",\n        \"default\": \"./",
 "/session.d.ts\",\n      \"default\": \"./",
 " \"./bun-sqlite/migrator",
 " \"./durable-sqlite/migrator",
 "`.\n         * @since v",
 "';\n         *\n         * const",
 " */\n        const SSL_OP_NO",
 "{\n  \"name\": \"",
 "\",\n  \"description\": \"",
 ")](https://",
 ")](https://www.npmjs.com/package",
 "\n```\n\n</details>\n<details><summary",
 "</summary><br>\n\nUse [dotenvx](",
 "summary><br>\n\nUse [dotenvx](https",
 "><br>\n\nUse [dotenvx](https://",
 "br>\n\nUse [dotenvx](https://github",
 ">\n\nUse [dotenvx](https://github.com",
 ")](https://github.com/dotenv-org",
 "- https://unpkg.com/gpt-tokenizer",
 " https://unpkg.com/gpt-tokenizer/dist",
 "](https://github.com/microsoft/TypeScript",
 "https://github.com/vercel/next.js",
 ".\n     * @",
 " NonSharedBuffer } from \"node:buffer\";\n",
 "SharedBuffer } from \"node:buffer\";\n   ",
 "Buffer } from \"node:buffer\";\n    import",
 "2011 23:24:11 GMT,\n",
 "1 23:24:11 GMT,\n    ",
 " 23:24:11 GMT,\n     *",
 "23:24:11 GMT,\n     *  ",
 "time: Mon, 10 Oct 2011",
 "(): boolean;\n        /**\n         * Returns `true",
 " boolean;\n        /**\n         * Returns `true`",
 ";\n        /**\n         * Returns `true` if",
 " * @since v12.12.0\n",
 ")`](http://man7.org/linux/man-pages",
 "](http://man7.org/linux/man-pages/man",
 "-headers\"?: string | undefined;\n        \"",
 "headers\"?: string | undefined;\n        \"access",
 " string | undefined;\n        \"sec-websocket-",
 " undefined;\n        /**\n         * If set to `",
 ";\n        /**\n         * If set to `true",
 ":\n         *\n         * ```js\n         *",
 " } from 'node:events';\n         *\n        ",
 " from 'node:events';\n         *\n         *",
 " number;\n        /** Instructs OpenSSL to disable",
 ";\n        /** Instructs OpenSSL to turn off",
 " `result`.\n     * * Otherwise, if `",
 "result`.\n     * * Otherwise, if `url",
 " not `undefined` and is not a string,",
 " `undefined` and is not a string, an",
 "undefined` and is not a string, an `",
 "` and is not a string, an `Error",
 " and is not a string, an `Error`",
 " is not a string, an `Error` is",
 " not a string, an `Error` is thrown",
 " a string, an `Error` is thrown.\n",
 "` is appended to `result`.\n     *   ",
 " appended to `result`.\n     *    * The",
 " to `result`.\n     *    * The value",
 " `result`.\n     *    * The value of",
 "result`.\n     *    * The value of `",
 "`.\n     *    * The value of `url",
 "     *    * The value of `urlObject",
 "` is appended to `result`.\n     * *",
 " is appended to `result`.\n     * * Otherwise",
 ".\n             * @throws {TypeError} if `",
 " @throws {TypeError} if `path` is",
 "throws {TypeError} if `path` is not",
 " {TypeError} if `path` is not a",
 "TypeError} if `path` is not a string",
 "\": \">=",
 "  \"keywords\": [\n    \"",
 "  \"homepage\": \"https://",
 "\"\n  },\n  \"peerDependencies",
 " \"engines\": {\n    \"node\": \"",
 "engines\": {\n    \"node\": \">=",
 ".ts' --env 'outDir=dist'",
 "' --env 'outDir=dist' --",
 " --env 'outDir=dist' --env",
 "env 'outDir=dist' --env '",
 " 'outDir=dist' --env 'module",
 "outDir=dist' --env 'moduleTarget",
 "Dir=dist' --env 'moduleTarget=",
 "=dist' --env 'moduleTarget=umd",
 "dist' --env 'moduleTarget=umd'",
 "' --env 'moduleTarget=umd' --",
 " --env 'moduleTarget=umd' --env",
 "env 'moduleTarget=umd' --env '",
 " 'moduleTarget=umd' --env 'engine",
 "moduleTarget=umd' --env 'engineTarget",
 "Target=umd' --env 'engineTarget=",
 "=umd' --env 'engineTarget=web",
 "umd' --env 'engineTarget=web'",
 "' --env 'engineTarget=web' --",
 " --env 'engineTarget=web' --env",
 "env 'engineTarget=web' --env '",
 " 'engineTarget=web' --env 'code",
 "engineTarget=web' --env 'codeTarget",
 "Target=web' --env 'codeTarget=",
 "=web' --env 'codeTarget=es",
 "web' --env 'codeTarget=es202",
 "' --env 'codeTarget=es2022",
 " --env 'codeTarget=es2022'",
 "env 'codeTarget=es2022' --",
 " 'codeTarget=es2022' --env",
 "codeTarget=es2022' --env '",
 "Target=es2022' --env 'name",
 "=es2022' --env 'name=G",
 "es2022' --env 'name=GPT",
 "2022' --env 'name=GPTTokenizer",
 ".mjs\"\n    },\n    \"./",
 "-sqlite/index",
 "/index.js\"\n    },\n    \"./",
 "-sqlite/migrator.d",
 " \"types\": \"./gel-core/",
 " \"default\": \"./gel-core/",
 "\": \"./better-sqlite3/migrator",
 "\": \"./bun-sqlite/migrator",
 "\": \"./durable-sqlite/migrator",
 "\": {\n        \"types\": \"./gel-core/",
 ";\n    }\n    interface",
 "         * @default ",
 ".0.0\n",
 " {@link",
 " | null;\n       ",
 "     *   //",
 "\": \"^2.",
 ".js)\n */\ndeclare module \"",
 "0n,\n     *  ",
 ".0\n         * @",
 " boolean;\n            /**\n             *",
 " the value of `urlObject",
 "     *    * If the",
 "\",\n  \"version\": \"",
 " will be",
 "/tailwindlabs/tailwindcss",
 "?: boolean | undefined;\n    }\n   ",
 "'\n     * ```\n     *\n     *",
 ".0\n     */\n    export function",
 " \"./better-sqlite3/driver",
 "/driver.js\"\n    },\n    \"./",
 " \"./bun-sql/migrator",
 " \"./bun-sqlite/driver",
 " \"./durable-sqlite/driver",
 " \"./expo-sqlite/migrator",
 ".com/tailwindlabs/tailwindcss",
 "`.\n         *\n         *",
 "(): this;\n        /**\n         *",
 "timeMs: 1318289051000",
 " | undefined;\n    }\n    interface",
 " boolean | undefined;\n        /**\n         * If",
 "             * @param",
 "         * @since v0.9.",
 ".2.",
 "         *   console.log",
 "\n         * @param",
 " const ee = new EventEmitter();\n        ",
 "         * ```\n         *\n         *",
 ";\n        /**\n         * The `subprocess",
 ":\n     *    * If the",
 "     *    * If the `urlObject",
 "` is not a string.\n             */\n           ",
 "Dependencies\": {\n   ",
 "  \"scripts\": {\n    \"",
 "\",\n  \"exports\": {\n    \".\":",
 "  },\n  \"scripts\": {\n    \"",
 "\": \"beemo webpack --entry='./src",
 ".js\"\n    },\n    \"./d",
 "\": \"./better-sqlite3/driver",
 "\": \"./bun-sql/migrator",
 "\": \"./bun-sqlite/driver",
 "-sqlite/migrator.d.ts\",\n",
 "\": \"./durable-sqlite/driver",
 "\": \"./expo-sqlite/migrator",
 "\",\n        \"default\": \"./gel-core/",
 "1.0",
 ");\n         *",
 " the child process",
 ",\n  decode,\n  isWithinTokenLimit,\n",
 "  decode,\n  isWithinTokenLimit,\n ",
 " from 'gpt-tokenizer/model/gpt-",
 "'\n\nconst text = 'Hello, world!'\nconst",
 ".3.0",
 ".\n     * @since v",
 " * @since v22.",
 "\" {\n    import { NonSharedBuffer } from",
 " {\n    import { NonSharedBuffer } from \"",
 "    import { NonSharedBuffer } from \"node",
 " import { NonSharedBuffer } from \"node:",
 " { NonSharedBuffer } from \"node:buffer",
 " } from \"node:buffer\";\n    import *",
 " from \"node:buffer\";\n    import * as",
 " \"node:buffer\";\n    import * as stream",
 " EventEmitter } from \"node:events\";\n    import",
 "     * ```\n     * @since v0.",
 "         * @since v12.12.0",
 " @since v12.12.0\n        ",
 " * @since v14.3.0,",
 " @since v14.3.0, v",
 "since v14.3.0, v12",
 " v14.3.0, v12.",
 "14.3.0, v12.20",
 ".3.0, v12.20.",
 "3.0, v12.20.0",
 ".0, v12.20.0\n",
 ".\n         * @default ",
 " * @since v18.",
 "        /**\n         * If set to `true`,",
 "?: boolean | undefined;\n        /**\n         * If",
 "             * The `readable",
 "https://nodejs.org/docs/latest-v22.x",
 "://nodejs.org/docs/latest-v22.x/api",
 " * @since v0.9.4\n",
 "';\n         *\n         * const ee = new EventEmitter",
 "         *\n         * const ee = new EventEmitter();\n",
 " *\n         * const ee = new EventEmitter();\n        ",
 " const ee = new EventEmitter();\n         *\n         *",
 "     * });\n     * ```\n     * @since",
 " * });\n     * ```\n     * @since v",
 " * import { spawn } from 'node:child",
 " import { spawn } from 'node:child_process",
 " { spawn } from 'node:child_process';\n",
 ": string | null;\n       ",
 " *\n     * ```js\n     * import url",
 "     * ```js\n     * import url from",
 " * ```js\n     * import url from '",
 " ```js\n     * import url from 'node",
 "js\n     * import url from 'node:url",
 "\n     * import url from 'node:url';\n",
 "     * import url from 'node:url';\n    ",
 "             *\n             * @param",
 "} if `path` is not a string.\n",
 " if `path` is not a string.\n            ",
 " `path` is not a string.\n             */\n",
 "path` is not a string.\n             */\n           ",
 "'],\n     * //   [",
 "     *\n     * ```js\n     * util",
 " *\n     * ```js\n     * util.format",
 "\": \"^3.",
 "\": \"^1.0.",
 "  },\n  \"repository\": {\n    \"type",
 " },\n  \"repository\": {\n    \"type\":",
 "\": \"git\",\n    \"url\": \"git",
 "\"\n  },\n  \"peerDependencies\": {\n   ",
 "\",\n  \"exports\": {\n    \".\": {\n",
 "\": \"beemo webpack --entry='./src/",
 " \"beemo webpack --entry='./src/encoding",
 "\": {\n      \"react-server\": \"./server.react",
 " {\n      \"react-server\": \"./server.react-server",
 "      \"react-server\": \"./server.react-server.js",
 " \"react-server\": \"./server.react-server.js\",\n",
 "react-server\": \"./server.react-server.js\",\n     ",
 "-server\": \"./server.react-server.js\",\n      \"",
 "-sqlite/driver.d",
 ".js\"\n    },\n    \"./expo-sqlite",
 " \"import\": {\n        \"types\": \"./expo",
 "import\": {\n        \"types\": \"./expo-s",
 ".d.ts\",\n        \"default\": \"./expo-s",
 ".ts\",\n        \"default\": \"./expo-sql",
 " \"require\": {\n        \"types\": \"./expo",
 "require\": {\n        \"types\": \"./expo-s",
 ".d.cts\",\n        \"default\": \"./expo",
 ".cts\",\n        \"default\": \"./expo-s",
 "js\"\n      },\n      \"types\": \"./expo",
 "\"\n      },\n      \"types\": \"./expo-s",
 "      },\n      \"types\": \"./expo-sql",
 " },\n      \"types\": \"./expo-sqlite",
 ".d.ts\",\n      \"default\": \"./expo-s",
 ".ts\",\n      \"default\": \"./expo-sql",
 "\",\n      \"default\": \"./expo-sqlite",
 "](https://img.shields.io",
 "https://github.com/niieani",
 "](https://www.typescriptlang.org",
 "https://github.com/tailwind",
 "\";\n    import {",
 " the\n     *",
 " *     console.log",
 ".0\n         */\n        readonly",
 " | null;\n        /**\n         *",
 " () => void): this;\n       ",
 " * @since v0.5.",
 "         * @since v18.",
 "         * @default false\n        ",
 "'` event",
 ": boolean;\n            /**\n             *",
 "         * });\n         *\n         *",
 " of the `spkac`",
 ".\n     * @since v0.",
 " from 'node:child_process';\n        ",
 "): string;\n    /**\n     *",
 " string:\n     *    * If the",
 " string;\n            /**\n             * The",
 ".\n             *\n             * @param",
 "             *\n             * @param path",
 "): string;\n            /**\n             *",
 " string): string;\n            /**\n             *",
 "     * //   [0, '",
 "\",\n    \"./",
 "  \"files\": [\n    \"",
 ".0.3\",\n    \"",
 "  \"devDependencies\": {\n   ",
 "    \"./package.json\": \"./package.json",
 "  \"devDependencies\": {\n    \"@",
 " \"./better-sqlite3/session",
 "/session.js\"\n    },\n    \"./",
 " \"./bun-sql/driver",
 " \"./bun-sqlite/session",
 " \"./durable-sqlite/session",
 " \"./expo-sqlite/driver",
 "0.10.0\",\n    \"@",
 "\": \"./better-sqlite3/index",
 "\": \"./better-sqlite3/session",
 "\": \"./bun-sql/driver",
 "-sqlite/driver.d.ts\",\n",
 "\": \"./bun-sqlite/index",
 "-sqlite/migrator.js\"\n",
 "\": \"./bun-sqlite/session",
 "\": \"./durable-sqlite/index",
 "\": \"./durable-sqlite/session",
 "\": \"./expo-sqlite/driver",
 ": string,",
 " src=\"https://img.shields.io/npm",
 " string;\n        /**\n         *",
 " from \"node:stream\";\n    import {",
 "         * @since v0.5.",
 " | undefined;\n        \"accept",
 "-encoding\"?: string | undefined;\n       ",
 "         * @default false\n         */\n       ",
 "\" | \"",
 "             *  ",
 ";\n            /**\n             * The `readable",
 "             *\n             * ```js\n             *",
 " => {\n         *  ",
 "         *\n         * The",
 "Options {\n        /**\n         *",
 "    /**\n     * The `",
 "        /**\n         * Returns the",
 "        /**\n         * ```js\n         *",
 "     *\n     * const",
 "         * assert.strictEqual(subprocess.stdio[",
 " `urlObject.search`",
 "\" {\n    import path = require(\"path",
 ": string): string;\n            /**\n             *",
 "'],\n     * //   [1, '",
 " `gpt-",
 " the\n         *",
 " the literal string `",
 "\",\n    \"build",
 ".js\",\n  \"",
 "\": \"^4.",
 "k_base",
 "         *    ",
 " to the",
 "/dotenvx/dotenvx) for",
 "://github.com/motdotla/dotenv",
 "https://github.com/niieani/gpt",
 "://github.com/niieani/gpt-token",
 "github.com/niieani/gpt-tokenizer",
 " 'gpt-tokenizer/model/gpt-4",
 "gpt-tokenizer/model/gpt-4o",
 "pt-tokenizer/model/gpt-4o'\n\n",
 " {\n  encode,\n  decode,\n  isWithin",
 "  encode,\n  decode,\n  isWithinToken",
 " encode,\n  decode,\n  isWithinTokenLimit",
 " decode,\n  isWithinTokenLimit,\n  //",
 ",\n  isWithinTokenLimit,\n  // etc",
 "  isWithinTokenLimit,\n  // etc...\n",
 " isWithinTokenLimit,\n  // etc...\n}",
 " } from 'gpt-tokenizer'\n\nconst text",
 " from 'gpt-tokenizer'\n\nconst text =",
 " 'gpt-tokenizer'\n\nconst text = '",
 "gpt-tokenizer'\n\nconst text = 'Hello",
 "pt-tokenizer'\n\nconst text = 'Hello,",
 "-tokenizer'\n\nconst text = 'Hello, world",
 "izer'\n\nconst text = 'Hello, world!'\n",
 "\"><img src=\"https://img.shields.io"
];
